### ISSUE TITLE
Serial2 not available on D0/D1 pins of Photon

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#101]
http://docs.particle.io/photon/firmware/#communication-serial

It’s actually on the BLUE and GREEN segments of the RGB led.  If using a P1, you can still use Serial2 and just move the status LED to 3 PWM outputs with some special code that repeats the LED status to those outputs.  If many PWMs are needed, you may can consider using a NeoPixel for a status LED which only requires one digital output.  PWM outputs will have a faster response though, and in theory the NeoPixel should not be updated from the interrupt that occurs to receive the RGB led status (i.e., the special code).  ...(I haven’t tried this yet, but in theory it should work… just requires more software.  It’s basically the NeoPixel library, but that can be seriously trimmed down for RGB status use.)

**Comment by m-mcgowan** [comment]
This has recently come up in the forum.

https://community.particle.io/t/using-serial2-results-in-undefined-behaviour/15545/4

I think it's best we simply state that Serial2 isn't available on the photon until there is a way to disable the default LED pins.

**Comment by technobly** [comment]
@m-mcgowan I was able to use Serial2 with the Photon without disabling the system LED (RGB.control(false)), but the 1k ohm series resistors on the BLUE and GREEN segments of the RGB need to be removed.  Otherwise, the TX will feed back into the RX pin.  Super weird, but it makes sense because LEDs can receive light and convert that light into a current, just the same way they can generate light when supplied with a current.  Once you overwrite the functionality of the RGB's BLUE and GREEN pins with Serial2's initialization code, they will remain that way until some other piece of code reinit's them for something else.  So I don't think there's a way for that to happen to the RGB LED output pins after the system boots.  It's available, you just have to do a little work to use it effectively.

**Comment by dseemakurty** [comment]
If I am understanding this correctly, in order to use the Serial 2 on the photon:
1. Remove the 1k ohm resistors on Blue on Green Segment
2. Connect to Blue and Green pads on bottom of photon
3. Include Serial2.h and initialize Serial2 to override the RGB

And if we want the RGB LED's back, we must utilize the RGB onChange handler to move the Blue and Green segments to 2 other PWM pins? (could we use D0 and D1?)

**Comment by technobly** [comment]
Yes that's correct @dseemakurty, please see the docs here:
https://docs.particle.io/reference/firmware/photon/#serial

**Comment by rcaudill** [comment]
Can anyone point me to the resistors on the photon (or a schematic) that should be removed?

**Comment by ericyuanyong** [comment]
Hey
Based on the document, it says you need to remove the limit current
resistor of Blue and Green Led. Which is R7 and R2 from the Schematic,
So if you check the PCB, it's the two resistor close to the 3V3 and RST on
header.

[image: Inline image 1]

**Comment by rcaudill** [comment]
Thanks for the reply. The image you posted isn't showing up, do you mind double checking it? 
I ended up just removing the RGB LED so I don't think wiring is a problem any more but it's still not working for me. I have a feeling I'm missing something in software. I put together a simple program to test. I've got D0 and RX wired together. Serial1 is showing the data but Serial2 isn't getting anything.

```
#include "Serial2/Serial2.h"

int led1 = D7;

void setup() {
  //pinMode(RGBR, OUTPUT);
  //RGB.control(true);
  //RGB.color(0, 0, 0);

  Serial1.begin(57600);
  Serial2.begin(57600);

  pinMode(led1, OUTPUT);
}

void loop() {
  if (Serial1.available() > 0) {
        String buffer = "";
        while (Serial1.available() > 0) {
            buffer.concat((char)Serial1.read());
        }
        Particle.publish("SERIAL1 GPS", buffer, PRIVATE);
  }

  if (Serial2.available() > 0) {
        String buffer = "";
        while (Serial2.available() > 0) {
            buffer.concat((char)Serial2.read());
        }
        Particle.publish("SERIAL2 GPS", buffer, PRIVATE);
  }

  digitalWrite(led1, HIGH);
  delay(1000);
  digitalWrite(led1, LOW);
  delay(1000);
}
```

Does this look right?

**Comment by technobly** [comment]
@rcaudill I'm guessing you are thinking Serial2 is available on D0/D1 like it is for the Core.  However on the Photon that is not the case, instead Serial2 is available on pins 28/29 on the bottom of the PCB: which are the Green and Blue RGB led segment outputs: https://docs.particle.io/datasheets/photon-datasheet/#recommended-pcb-land-pattern-photon-without-headers- and also requires isolating the lines (either removing the Blue/Green segment resistors or the RGB led as you have).

A good way to test this is with a loopback setup through USB serial.  Anything you type in a USB serial terminal will be echoed through Serial2 TX-RX and back to USB serial.

``` cpp
// Make sure to short pin 28(TX) to 29(RX) (Serial2 TX to RX for loopback mode)
#include "Serial2/Serial2.h"

void setup()
{
  Serial.begin(9600);
  Serial2.begin(9600);
}

void loop()
{
  // read from Serial (USB), send to Serial2:
  if (Serial.available())
  {
    char c = Serial.read();
    Serial2.write(c);
  }
  // read from Serial2, send to Serial (USB):
  if (Serial2.available())
  {
    char c = Serial2.read();
    Serial.write(c);
  }
}
```

**Comment by rcaudill** [comment]
Yup, I was using D0/D1... Using the pad on the bottom of the PCB worked! Thanks guys!
