### ISSUE TITLE
Device Doctor Present on Gen3 Status LED Pages

### ISSUE THREAD

**Issue by marekparticle** [particle-iot/docs#1019]
Under "Out Of Heap Memory" Error the Device Status LED Tutorial Pages, instructions are given to run `particle device doctor`. As this function does not currently work on Gen3 Devices, this can be misleading to customers already dealing with the complexity of a Red SOS. 

https://docs.particle.io/tutorials/device-os/led/argon/#red-flash-sos
https://docs.particle.io/tutorials/device-os/led/boron/#red-flash-sos
https://docs.particle.io/tutorials/device-os/led/xenon/#red-flash-sos

This instruction should be removed or otherwise altered.

**Comment by rickkas7** [comment]
Fixed via this commit: 
https://github.com/particle-iot/docs/commit/cbd7a5021553b6239fbed244f7eec4282e281de8
