### ISSUE TITLE
last_heard should be marked as deprecated for Device List

### ISSUE THREAD

**Issue by edalquist** [particle-iot/docs#105]
Context: https://community.particle.io/t/last-heard-stale-in-device-list/14116

Bad Content: https://docs.particle.io/reference/api/#list-devices

I'd send a pull request but I don;t know where that content is coming from. The api.md file just has a placeholder: {{> api group=apiGroups.Devices}}

**Comment by kennethlimcp** [comment]
@dmiddlecamp i don't have access to the private repo for `api-node` so will you be able to open an issue there?

**Comment by dmiddlecamp** [comment]
sure, created an issue to track this

**Comment by monkbroc** [comment]
This is fixed in the API now.
