### ISSUE TITLE
Argon's high-res PDF Pinout Diagram depicts Xenon instead

### ISSUE THREAD

**Issue by favict** [particle-iot/docs#1059]
In [Argon Datasheet](https://github.com/particle-iot/docs/blob/master/src/content/datasheets/wi-fi/argon-datasheet.md), section **Pinout diagram**, the high-res PDF references to [this](https://docs.particle.io/assets/images/argon/argon-pinout-v1.0.pdf) PDF file which depicts a Xenon device instead of an Argon device. 

![argon_pinout](https://user-images.githubusercontent.com/45994341/71822871-bf2da280-3074-11ea-8107-60cb50f87d82.png)

**Comment by rickkas7** [comment]
Thanks for the report. It should be fixed. It affected both Argon and Boron. It only affected some browsers. Firefox for sure, possibly others.
