### ISSUE TITLE
cli.md needs link to cli installation instructions

### ISSUE THREAD

**Issue by gitcnd** [particle-iot/docs#111]
The CLI doc jumps right into examples, none of which work of course, without the CLI first being installed, but no hint of how to do this exists in this doc.

It should be at the start...

**Comment by moors7** [comment]
What about this? https://docs.particle.io/guide/tools-and-features/cli/#installing
Or am I looking in the wrong place?

**Comment by gitcnd** [comment]
I'm not saying it doesn't exist, somewhere in the bowels of an alpha-centurion council depot... I'm saying that the doc about how to use the CLI needs to start with instructions about how to INSTALL the cli.  If those are they - put them, or a link to them, into the doc, at the start...

Even better - give us some non-rocket-science non-timewasting way to fix that ourselves, then we don't have to waste time telling others to fix it - we can just fix it _for_ you...

Can the doc be edited like a wiki?

**Comment by moors7** [comment]
So I guess I was looking in the wrong place... I think you're referring to the "reference" section of the docs? Considering there is [more than one](https://github.com/spark/docs/blob/master/src/content/guide/tools-and-features/cli.md) "CLI.md" it might be worthwhile pointing out to which you're referring.
When you say the docs need to start with telling you how to install it, I'm inclined to say that they do, considering you land in the "guide" part of the docs, which has a section dedicated to the CLI, and how to install it. They end with:"For more info on CLI commands, go here.", which gets you to the reference section. 
That said, I can see where you're coming from, and several of the other things in the reference have installation instructions included. I'm assuming you'd like the install instructions to be linked to from the reference part of the docs, right?

You can certainly propose changes to the docs by clicking the "edit" button in the top right corner of the relevant page. That'll get you to the corresponding GitHub page where you can issue a pull request.

**Comment by kennethlimcp** [comment]
@gitcnd, thanks for the feedback. I understand where you are coming from. Have suggested and waiting got more inputs before deciding if the entire docs for installation with be included for CLI.

Closing this and focusing on: https://github.com/spark/docs/issues/128
