### ISSUE TITLE
this is an issue

### ISSUE THREAD

**Issue by hunterthedog** [particle-iot/docs#117]
christine is not wearing a hat and that makes me sad

**Comment by ScruffR** [comment]
NIce issue ;-)

**Comment by moors7** [comment]
Don't be sad, everything will be okay :)
![christine_hat](https://cloud.githubusercontent.com/assets/6599791/9239305/b083afda-415a-11e5-8fe6-8e493338c3d5.png)

**Comment by cmsunu28** [comment]
awwwww
