### ISSUE TITLE
api-node module missing?

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/docs#125]
When I check out the repository, I can't update the api-node submodule because https://github.com/spark/api-node returns 404 not found. Is it a private repository? Why do you have this in the public docs repo?

It's not a big deal, but I get an error `fatal: repository 'https://github.com/spark/api-node/' not found` every time I pull new commits.

**Comment by kennethlimcp** [comment]
@brycekahle can you comment about this? I get this once in a while as well.

**Comment by brycekahle** [comment]
It is a private repo. We have some auto generated API documentation based on it.

**Comment by kennethlimcp** [comment]
Is there someway to suppress the error? What i do locally is to untrack the `api-node` under git but that's a little weird for developers wanting to help and contribute

**Comment by brycekahle** [comment]
I'll see if I can add some instructions to avoid the error.

**Comment by monkbroc** [comment]
Fixed now in `master`. This one is for you @kennethlimcp since you help so much with the docs. :heart:

**Comment by kennethlimcp** [comment]
woohoo thanks @monkbroc!
