### ISSUE TITLE
No reference in docs how to install DFU drivers on Windows

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/docs#128]
A member was convinced to have done everthing according docs to perform something like `particle flash --usb tinker`, but couldn't get it to work.

When checking the docs I found that these parts of the docs do create the impression that the `Spark.zip` drivers suffice to allow for _all_ `particle` commands, which they don't.

https://docs.particle.io/guide/getting-started/connect/core/#using-windows
https://docs.particle.io/guide/getting-started/connect/photon/#using-windows

A section about the installation of DFU drivers would be good.
I'd do a PR refering to `zadig`, but I'm not sure if this still is the official way to do it.
If not it would be useful to package the DFU drivers into `Spark.zip`.

**Comment by kennethlimcp** [comment]
@ScruffR I have a tutorial for DFU in the community if linking to that helps. The docs is missing the HowTo install DFU in the guide section

**Comment by ScruffR** [comment]
I guess this would at least be a good starting point.

**Comment by kennethlimcp** [comment]
@cmsunu28,

I would love your input here. Should we write down explicitly on how to install the entire CLI and it's dependencies (since it is called a `guide`)? Won't mind doing this by grabbing the content from my tutorials instead of directing people there (the guide should _guide_ them to install without external resources)

**Comment by moors7** [comment]
I think having something official in the guide is good. All essential information should come from a verified source, in this case the docs. (That's not to say yours is not verified, Kenneth :O). Any additional, or 'personal experience' information is okay for the forums, as longs as there's an 'official' path to follow.
Related to this topic in the way that people are eager for a concentrated source of verified information, in which they can find all essential tools/guidance they need to get up and running: http://community.particle.io/t/what-is-the-official-preffered-most-robust-most-effective-method-to-flash-firmware/15296

Incorporating some of the known areas of problems wouldn't be bad either. "if stuff fails, try running it as sudo", and "if it starts complaining about serialport missing, try installing that first".

**Comment by cmsunu28** [comment]
Hey @kennethlimcp if you show me the basics of what you mean I can take a deeper look. Point me to your post?

**Comment by kennethlimcp** [comment]
https://community.particle.io/t/tutorial-particle-cli-on-mac-osx-07-jun-2015/5225

https://community.particle.io/t/tutorial-particle-cli-on-windows-07-jun-2015/3112

**Comment by monkbroc** [comment]
Closing old issues
