### ISSUE TITLE
Factory reset docs are inaccurate

### ISSUE THREAD

**Issue by MartyMacGyver** [particle-iot/docs#138]
From here:
https://docs.particle.io/guide/getting-started/modes/photon/#factory-reset
1. Hold down BOTH buttons
2. Release only the RESET button, while holding down the SETUP button.
3. Wait for the LED to start flashing magenta, then yellow, then green (continue to hold the SETUP button)
4. The LED will turn solid white (continue to hold the SETUP button)
5. Finally, the LED will turn blink white rapidly
6. Release the SETUP button

However, the solid/blinking white bit is not correct. It should read:
1. Hold down BOTH buttons
2. Release only the RESET button, while holding down the SETUP button
3. The LED will start flashing magenta, then flashing yellow, then flashing green (continue to hold down the SETUP button)
4. When the LED flashes white, release the SETUP button
5. The LED will turn solid white as the device is factory reset
6. Finally, the LED will blink blue as the device awaits initial setup

**Comment by kennethlimcp** [comment]
Closing this since the description was updated here: https://github.com/spark/docs/commit/efed4c861695156cb00606e2ee9f298a9da1b509
