### ISSUE TITLE
Document webhooks `responseTemplate` option

### ISSUE THREAD

**Issue by mathiasschopmans** [particle-iot/docs#149]
Currently this option seems undocumented. It would be nice to mention this in  https://docs.particle.io/guide/tools-and-features/webhooks/#webhook-options

Found a example usage in the community: https://community.particle.io/t/cloud-json-parsing/11223/2

``` json
{
"eventName": "some_event_name",
"url": "http://api.openweathermap.org/data/2.5/forecast/daily",
"requestType": "POST",
"headers": null,
"query": {
    "q": "Ottawa,ON",
    "mode": "json",
    "units": "metric",
    "cnt": 7
    },
"responseTemplate": "{{#list}}{{temp.day}}{{#weather}}~{{id}}~{{main}}~{{/weather}}{{/list}}",
"json": null,
"auth": null,
"mydevices": true
}
```

I'm also interested wether this technique works for XML responses.
Thanks.

**Comment by monkbroc** [comment]
This is documented now!
