### ISSUE TITLE
Shields docs feedback

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#152]
- [x] **Power shield**
- v2.1.0
- [ ] stat1 and stat2 LED should be documented of it's represented function
- [x] **Relay Shield**
- v3.1.0
- [x]  Should mention in docs that the control pins can be disabled by cutting in between each pad

**Programmer Shield**
- [x]  does not mention which pins of the Photon/Core does the UART connect to.

**Comment by kennethlimcp** [comment]
@mohitbhoite let me know how i can help here. I can make the image for the relay shield issue but someone needs to tell me about stat1 and stat2 led for power shield

**Comment by kennethlimcp** [comment]
From the datasheet:

<img width="590" alt="screen shot 2015-09-11 at 17 19 14" src="https://cloud.githubusercontent.com/assets/6760914/9811623/fb25d8bc-58aa-11e5-9bc7-c03d90511fa7.png">

Will create a table accordingly.

**Comment by ScruffR** [comment]
Do these directly correspond to the two LEDs (red/blue)?

Having this table is one thing, but users might not see it quite this technical.
e.g. having the shield powered via USB with a Photon in it but battery not attached connected (propperly) does show red with a short flash of blue - how would I see that from the table?
When doing this the first time after having the shield unpowered for a longer while, produces a very rapid alternating flashing of red and blue.

This might be symptoms users might look for in the docs.

**Comment by kennethlimcp** [comment]
That's good input. let me read the datasheet further ;)
- [ ] Unable to find information about rapid blue and red blinking without battery attached
