### ISSUE TITLE
Rename driver to Particle.zip

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#158]
@joegoggins will you be able to handle this?

`https://docs.particle.io/guide/getting-started/connect/core/#installing-the-particle-driver`

**Comment by joegoggins** [comment]
Thanks for bringing this up, will do.

@brycekahle , @technobly : My plan is to 1) Rename the S3 file, 2) add an S3 redirect, and 3) change the docs to point at the new one. I'm assuming this name change won't have any downstream issues, let me know if not.

**Comment by kennethlimcp** [comment]
Tested working with: https://github.com/spark/docs/commit/fb35c5f4a51da5aeb77ec640cf1683cd382c9b8a

Spark.zip and Particle.zip are both ok via direct link download so closing. Thanks @joegoggins!

**Comment by joegoggins** [comment]
Done.

**Comment by joegoggins** [comment]
No problem K!
