### ISSUE TITLE
Search requires user to know full function name

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#159]
I was searching for `selectAntenna` and returned no result but `WiFi.selectAntenna` worked fine.

**Comment by m-mcgowan** [comment]
In looking through the docs now, there's an inconsistency between some functions using the class name as a prefix, and others that don't. 

For example, WiFi functions are all written with the prefix, but those for UDP/TCP aren't. Ideally we'd be consistent in all cases. Independently of what we decide there though, I give a :+1:  that the search should also find the function without the prefix - if you have to write the prefix it assumes you also know exactly what you're looking for, which isn't always the case.

**Comment by technobly** [comment]
I think we should strive to include the class name when appropriate but also find a way to make the search function search member function names.
