### ISSUE TITLE
Refactor discussion

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#161]
There are some information at incorrect places that should be factored out
- Programmer shield usage should go under Guide/reference
- new shields are not specific to the Photon and should be listed by itself in Datasheet

**Comment by cmsunu28** [comment]
I believe that the programmer shield should not go in the guide until there are clear step-by-step examples that go with it.

Reference is mainly for code.

Datasheets are supposed to be descriptions of hardware with the basic run-down.

**Comment by cmsunu28** [comment]
Hiya! Was looking into this again today, I am keeping this issue open so that we make sure we create guide/reference content for the programmer shield.
