### ISSUE TITLE
Glossary of things

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#165]
Where should all these go?
- Cloud public key download link (https://s3.amazonaws.com/spark-website/cloud_public.der)
- Unlocker/locker bin
- RGB led colour representation (blinking white, magenta..)
- Photon memory map (https://github.com/spark/docs/issues/82)
- DFU command list (https://github.com/spark/docs/wiki/DFU-reference)
- Document listening mode commands (https://github.com/spark/docs/issues/179)
- Number of Wifi network you can connect to for each Device
- Photon memory map (https://github.com/spark/docs/issues/82)

**Comment by cmsunu28** [comment]
OK going through these, rewriting as check-offable things:
- [x] Cloud public key download link: I think this should go in troubleshooting which is a whole pending update, as we talked about previously
- [ ] Unlocker/locker bin: Created a section for this content in https://github.com/spark/docs/tree/feature/fundamentals
- [x] RGB led colors: this is currently in both troubleshooting and modes: https://docs.particle.io/support/troubleshooting-support/photon/ https://docs.particle.io/guide/getting-started/modes/photon/#troubleshooting-modes
- [ ] Photon memory map: sounds like Brett is working on this now https://github.com/spark/docs/issues/19
- [x] DFU commands: will be in troubleshooting as something like "if cli doesn't work, these are equivalent DFU commands"
- [x] Listening mode commands: this should be in troubleshooting
- [X] # networks for each device: it's 5, this is listed in the scroll-over in this section https://docs.particle.io/guide/getting-started/start/photon/#step-2-connect-with-your-smartphone
