### ISSUE TITLE
Remove Photon factory reset notes

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#167]
https://docs.particle.io/support/troubleshooting-support/photon/#led-colors-explained-

**Comment by chobberoni** [comment]
can you comment further on this? @kennethlimcp

**Comment by kennethlimcp** [comment]
@chobberoni, just thinking about it. Factory reset is no longer available (or rather behaves differently but i think the docs can still stay) this is what i updated it to so gonna close this - https://github.com/spark/docs/pull/168/files

Let me know what you think!

**Comment by chobberoni** [comment]
you're right @kennethlimcp ! we (rich and I) were just talking about this the other day.
