### ISSUE TITLE
Device selection disappears below 1st category

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#169]
When you first visit the top category (guide, reference, datasheet, support), you will notice the device selection. Clicking on the 2nd sub category and below it disappears.

<img width="1253" alt="screen shot 2015-09-11 at 08 56 11" src="https://cloud.githubusercontent.com/assets/6760914/9804690/fcf1d35a-5862-11e5-9d3a-e1bf50dd7446.png">

**Comment by brycekahle** [comment]
That is because you selected a page that is specific to one device.

**Comment by kennethlimcp** [comment]
@brycekahle  what... So i cannot do conditional below the first category and this is considered closed?

I am using the conditional here and it is not picking up which device is selected:

<img width="1176" alt="screen shot 2015-09-11 at 09 03 17" src="https://cloud.githubusercontent.com/assets/6760914/9804803/f94063ba-5863-11e5-99f9-3189aec16c2c.png">

**Comment by brycekahle** [comment]
You selected the "Core datasheet". There is no Photon version of the Core datasheet. If you visit https://docs.particle.io/guide/getting-started/connect/photon/ you see the device selector is still there.

Each page has metadata to indicate if there are multiple device specific versions. If not, no selector is shown.
