### ISSUE TITLE
Photon: analogWrite() for DAC requires pinMode() each time 

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/docs#170]
I think this is rather a firmware issue (which I'll also open), but for the time being it seems necessary to add a comment that it's not enough to set `pinMode(DAC, OUTPUT)` only once but you need to do this each time before calling `analogWrite(DAC, val)`.

There is no mention about this behaviour here
https://docs.particle.io/reference/firmware/photon/#analog-output-photon-

But in this topic I've confirmed the finding of another member
https://community.particle.io/t/analogwrite-dac-only-once-for-each-pinmode-output/15393/2

**Comment by monkbroc** [comment]
This is fixed in the firmware now.
