### ISSUE TITLE
photon docs missing antenna select

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#173]
bool WiFi.antennaSelect(AUTO | INTERNAL | EXTERNAL);

**Comment by m-mcgowan** [comment]
https://docs.particle.io/reference/firmware/photon/#wifi-selectantenna-

it was originally cast as antennaSelect when the function was drafted, but later renamed to selectAntenna before release.

**Comment by dmiddlecamp** [comment]
is there something we can do to get it to show up when we search for "antenna"?

**Comment by m-mcgowan** [comment]
Yeah, that would be sweet! It's bit me a few times too. There's an issue for that here, https://github.com/spark/docs/issues/159

**Comment by dmiddlecamp** [comment]
lets ping the expert @jme783
