### ISSUE TITLE
Please mention nodejs version

### ISSUE THREAD

**Issue by kasperkamperman** [particle-iot/docs#176]
It seems that 4.0.0 doesn't work: maybe good to mention

https://docs.particle.io/guide/getting-started/connect/photon/#installing-node-js

https://community.particle.io/t/cant-install-particle-cli-osx-solved/15457/7

**Comment by kennethlimcp** [comment]
PR already here: https://github.com/spark/docs/pull/162

**Comment by kasperkamperman** [comment]
Ok. I will close this one then. Thanks.
