### ISSUE TITLE
Actual pictures and videos to take

### ISSUE THREAD

**Issue by cmsunu28** [particle-iot/docs#18]
- [x] In box photon birds eye
- [x] In box core birds eye
- [x] Photon plugged in birds eye
- [x] Core plugged in birds eye
- <10 sec video of Core in...
  - [x] listening mode
  - [x] trying to connect, then connected
  - [x] connected
  - [x] flashing
  - [x] dfu
  - [x] factory reset
  - [ ] any other modes...
- <10 sec video of Photon in...
  - [x] listening mode
  - [x] trying to connect, then connected
  - [x] connected
  - [x] flashing
  - [x] safe mode (magenta)
  - [x] dfu (yellow)
  - [x] replace firmware with factory reset but don't clear wifi
  - [x] factory reset
  - [ ] any other modes...
- [x] Birds eye picture of core alone top and botton
- [x] Birds eye picture of Photon top (and bottom for completeness)
- [ ] Core in breadboard wired for LED
- [ ] Photon in breadboard wired for LED
- [ ] Core in breadboard wired for temp
- [ ] Photon in breadboard wired for temp
- [ ] <10 sec video of Core of connecting with tinker
- [ ] <10 sec video of Core of blinking LED with tinker
- [ ] <10 sec video of Photon of connecting with tinker
- [ ] <10 sec video of Photon of blinking LED with tinker

**Comment by kennethlimcp** [comment]
@cmsunu28 will the images for shared resources like `firmware` be using a core or photon picture? I'm guessing it will be different on the electron as well so we might need to figure that as well.

One example is `SPI`: http://docs.particle.io/photon/firmware/#communication-spi

**Comment by kennethlimcp** [comment]
@cmsunu28 , i will close this if you don't need this list anymore? Let me know?
