### ISSUE TITLE
Extract firmware file name example

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#180]
This is a great example on how someone can extract the filename of the `xxxx.cpp` flashed to the particular device!

https://community.particle.io/t/particle-constant-for-current-running-application-name/15572/6

**Comment by kennethlimcp** [comment]
```
#define COMPILED_FILENAME __FILE__

const char * programVersion = COMPILED_FILENAME;

void setup()
{
  const char * fileName = (strrchr(programVersion,'/') + 1);
  Particle.variable("pgmVersion", fileName, STRING);
}
//
void loop()
{

}
```

**Comment by m-mcgowan** [comment]
What does pgmVersion evaluate to? It looks like the filename, so perhaps the variable could be called `appname` instead?

You might also want to advise users to create a version variable that they increment with each change, or alternatively use the built-in **DATE** and **TIME** macros:

```
void setup()
{
    // todo - what about Windows where the file separator is \
    Particle.variable("appname", strrchr((const char*)__FILE__, '/')+1);
    Particle.variable("version",  (const char*)(__DATE__ " " __TIME__), STRING);
}
```

**Comment by kennethlimcp** [comment]
@m-mcgowan that's great! Just wanted to open an issue to keep the conversation going so i think the Date and Time method would be good :)

```
void setup()
{
  const char * fileName = (strrchr(__FILE__,'/') + 1);
  char fileInfo[125] = "";
  sprintf(fileInfo, "Filename: %s compiled on %s at %s UTC", fileName , __DATE__ , __TIME__ );
  Particle.variable("pgmVersion", fileInfo, STRING);
}
//
void loop()
{

}
```

**Comment by m-mcgowan** [comment]
Close, but no cigar! ^^ that example will fail - the buffer passed to Particle.variable() will go out of scope when setup is exited, resulting in garbage for the variable value.  Either use only the predefined constants as I did in my example, or move the buffer to global scope.

**Comment by kennethlimcp** [comment]
Hehe. the funny thing is the community user used that code above and worked...
