### ISSUE TITLE
Unable to {{#if photon}} in popup

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#181]
So i am trying to update the incorrect Wifi credential count for Photon and i cannot seem to do it:

<img width="761" alt="screen shot 2015-09-16 at 20 21 14" src="https://cloud.githubusercontent.com/assets/6760914/9904474/931ad998-5cb0-11e5-97b8-6c631e3286bb.png">

Here: https://github.com/spark/docs/blob/master/src/content/guide/getting-started/start.md#step-2-connect-with-your-smartphone

**Comment by jme783** [comment]
While I can't deep dive into this immediately, I will say that device-conditionals will not work inside these popups, as they are inserted at run-time with client-side JS, and not pre-compiled at build time.

I would instead try to create two separate popups, one for the Core and one for the Photon. By placing the device conditionals _outside_ of the popup, you will be able to achieve the result you want. Something like this (untested):

```
{{#if photon}}
{{{ popup 'connect your device to Wi-Fi.' 'note' 'Your device remembers up to 5 wifi networks, and it will connect to these automatically if it can find them.'}}}
{{/if}}
{{#if core}}
{{{ popup 'connect your device to Wi-Fi.' 'note' 'Your device remembers up to 7 wifi networks, and it will connect to these automatically if it can find them.'}}}
{{if}}
```

**Comment by kennethlimcp** [comment]
:+1:

**Comment by kennethlimcp** [comment]
Closing, fixed with: https://github.com/spark/docs/commit/63387d8c61bdf5b7f863452041e2153f631deb08
