### ISSUE TITLE
SPI/SPI1 pins on Photon hard to understand

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#183]
Users have to look at the Pin-out diagram which says `SPI1` and `SPI3` and they have problem looking at the key legend on match the correct pins. (The colours are too close and the names are causing confusion since in firmware it is SPI/SPI1 and in hardware label it is SPI1/SPI3)

We need an updated pin-out map that labels the JTAG, SPI, SPI1, TX/RX if they are missing...

See: https://community.particle.io/t/spi-on-the-photon-confused/15623/2

**Comment by dougalcampbell** [comment]
I've put in a Pull Request to help clarify the docs: #184
