### ISSUE TITLE
No references to Python need

### ISSUE THREAD

**Issue by sixerdoodle** [particle-iot/docs#188]
Node.js requires that some version of Python is installed first.  That requirement isn't obvious from the existing docs and there are version issues.  Python 3.5 won't work, have to use 2.7

**Comment by kennethlimcp** [comment]
@sixerdoodle i am trying to recall why python is required. I think it will be the `node-serialport` package for CLI. Are you referring to CLI installation steps?

**Comment by wgbartley** [comment]
One of the dependencies relies on node-gyp which requires Python.  I'm not in front of a computer at the moment to double-check, but I'm betting it's the serial port package that needs to be compiled/built using node-gyp for the various platforms.

**Comment by sixerdoodle** [comment]
yes, "npm install -g particle-cli" requires python.  tried Python 3.5 first and it was better, but still busted  had to go back to Python 2.7.  Then the serial port package requires older Node.js
