### ISSUE TITLE
Firmware documentation can contain functions with the same name

### ISSUE THREAD

**Issue by m-mcgowan** [particle-iot/docs#192]
To the lords of the documentation. 

Currently in firmware we have several functions with the same name in the documentation.

For example, begin(), end() and format() - these functions appear in several libraries  Currently, the search results only shows one occurrence. Ideally it should show each occurrence,  plus the section that it appears in. 

Alternatively, we can prefix each function with the library it appears in, e.g. Serial.begin(), Serial1.begin(), Wire.begin(), TCP.begin(). At present, some libraries use their prefix (e.g. WiFi.on() while others don't.

**Comment by monkbroc** [comment]
The lords of documentation have provided.
