### ISSUE TITLE
PIR sensor Datasheet is in chinese

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#207]
Someone really needs to write information about the PIR like how to set the L/H instead of providing a chinese datasheet that not many can read:

https://docs.particle.io/datasheets/photon-shields/#pir-sensor-1-

https://docs.particle.io/assets/datasheets/makerkit/pir-sensor.pdf

**Comment by ericyuanyong** [comment]
It can be a problem if this guy did not have much experience on this sensor, In fact, the voltage on the output pin will change from Low to high when it detect the human body and it will be constant high for a defined time(which can be changed by changing the value of potentiometer) after it cannot detect human body.then, it will go back to low. In short, it will go to high instantly after it detect the human body and it will keep high for sends even it cannot detect the body and then it go back to low.
