### ISSUE TITLE
Internet Button BOM?

### ISSUE THREAD

**Issue by embedded-creations** [particle-iot/docs#222]
Is it possible to include the BOM for the Internet Button here like you do for the Photon Datasheet?
https://docs.particle.io/datasheets/photon-shields/

Specifically I'd like to know the SMT female headers used to connect the Photon to the board.  I think this is great design, allowing for low-profile mounting of the Photon without requiring soldering.  I plan to use this for Photon shields I'm going to design in the (hopefully near) future, and I imagine others will as well.

BTW, great design @jenesaisdiq.  I bought an Internet Button immediately after watching your Particle Interaction interview.

**Comment by jenesaisdiq** [comment]
Hey, thanks @embedded-creations! We usually put up a repo with the EAGLEs and BOMs but haven't had the time to clean up and release the photon-shields one yet. I can, however, answer your question! Those headers took me forever to figure out, and the ones are on the board are 3M 966224-2000-AR-PR. They're Really Pricey. I believe 4Ucon has a compatible part, and you'd hope for cheaper. I also have an EAGLE footprint for it, if you decide to use the part.

**Comment by embedded-creations** [comment]
You weren't kidding on the price!  Did you select that part for the height (tall enough to capture the Photon pins) or some other reason?  I was actually expecting some Chinese supplier number that would be hard to source, I was surprised to find it was 3M.  4U's part is shorter, and I asked for samples from my Chinese manufacturer (NOA Labs) and they found some that are 5mm like the 3M part, I can share info if you're interested after I get the parts and quote.

**Comment by jenesaisdiq** [comment]
Sure, I'd love to hear how well they work for you! 3M was mainly because we were on a tight deadline and I could both source them from Digikey to test and in China for production. The height's not too big a deal, shorter should work even better for rear entry.

**Comment by embedded-creations** [comment]
Any concerns on alignment during placement and reflow?  I could see the Photon not inserting easily if the PCB holes and socket weren't aligned well.  You sell the Internet Button with a Photon attached, so that would be caught, but I will likely sell shields without a Photon and just pogo pin tests which wouldn't carefully check for alignment.

**Comment by jenesaisdiq** [comment]
That was my biggest concern, actually. So far it hasn't been a problem, and I haven't heard about high rejection rates. Surface tension makes things align surprisingly well.

**Comment by embedded-creations** [comment]
Thanks for the info, I'll share my info hopefully next week.  Feel free to close this issue if you want, I'll find you in the Community.
