### ISSUE TITLE
Photon Datasheet missing test point description

### ISSUE THREAD

**Issue by embedded-creations** [particle-iot/docs#223]
The test points aren't described anywhere that I could find, I had to open the PCB design in Eagle to find that information.  The setup button and RGB LED are required to be user accessible, and that means using the test points if the Photon needs to be protected in the design, so I think these are especially important to include in the data sheet.

https://docs.particle.io/datasheets/photon-datasheet/#pin-and-button-definition

**Comment by technobly** [comment]
I'll make a note to add more of a description for test points, but for future reference they are numbered here:
![](https://docs.particle.io/assets/images/photon-pinout3.png)

And located here on the right side:
![](https://docs.particle.io/assets/images/photon_land_pattern_without_headers.png)

Thanks!

**Comment by embedded-creations** [comment]
Cool, I totally missed that info.  I was searching for "test" "smd" "bottom" and "button" which didn't pull up anything. "Button" is only in the pinout image.  Maybe give a caption to the pinout table image that says "SMD Test Points on Bottom of Photon PCB" or something like that?

You could add some of those keywords to this sentence too: "Photon Pin #25-31 are described in the Pin Out Diagrams." 

Thanks!

**Comment by technobly** [comment]
Added info to Photon Datasheet v013:

https://docs.particle.io/datasheets/photon-datasheet/#pin-description

https://docs.particle.io/datasheets/photon-datasheet/#recommended-pcb-land-pattern-photon-without-headers-
