### ISSUE TITLE
Runtime constraints on SPI DMA callback not documented

### ISSUE THREAD

**Issue by innermatrix** [particle-iot/docs#229]
I want to use the DMA variant of SPI transfer() function, but I am not sure what runtime constraints are imposed on the callback. Does it behave like an interrupt handler? Does it behave like normal code? Does it run from Particle.process()? Does it run on the system thread or the user thread?

**Comment by kennethlimcp** [comment]
This might be a question for https://community.particle.io or https://github.com/spark/firmware

**Comment by innermatrix** [comment]
[I asked it there and got an answer](https://community.particle.io/t/runtime-constraints-on-spi-dma-callback/17595), but the fact that this is missing from documentation is still a bug.
