### ISSUE TITLE
Document Thread and CriticalSection

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/docs#246]
The `Thread("label", handler)` way of starting a user thread and the `CriticalSection cs` helper are not documented in the firmware reference. This causes confusion when people see these discussed on the forum but can't find more details in the docs.

**Comment by m-mcgowan** [comment]
This is somewhat intentional - the thread API has not been finalized, but is a work in progress. I would like to review the API and set out all envisaged threading constructs before documenting it.
