### ISSUE TITLE
Problem with instructions to reset the keys on your device

### ISSUE THREAD

**Issue by rhyde** [particle-iot/docs#248]
If you haven't ever claimed the device before: You will need dfu-util. Install it, then download the this file. Use the command line to navigate to that file. Run the following command: dfu-util -d 2b04:d006 -a 1 -s 2082 -D cloud_public.der This should reset your public key.
If you claimed the device previously: You need the CLI. Once it is installed, run: particle keys server cloud_public.der particle keys new photon particle keys load photon.der particle keys send photon.pub.pem This should reset your public key.

The command given there are "particle keys send photon.pub.pem" fails every time with the error
Here is my cli log
Richs-iMac:Particle rich$ ls -l
total 48
-rw-r-----@ 1 rich  staff   402 Dec 13 12:57 cloud_public.der
-rw-r--r--  1 rich  staff   608 Dec 13 13:04 photon.der
-rw-r--r--  1 rich  staff   887 Dec 13 13:03 photon.pem
-rw-r--r--  1 rich  staff   272 Dec 13 13:03 photon.pub.pem
-rw-r--r--  1 rich  staff  1024 Dec 13 13:04 pre_photon.der
-rw-r--r--  1 rich  staff   272 Dec 13 13:04 pre_photon.pub.pem
Richs-iMac:Particle rich$ particle keys send photon.pub.pem
Please provide a filename for your device's public key ending in .pub.pem

This is just after having run the previous commands given there.  

Something is wrong in the send command as it rejects the valid filename it is given.

I tried to reset the keys as my device is stuck with a solid magenta light for over 12 hours.

**Comment by kennethlimcp** [comment]
This is more like a problem with the CLI and not the docs.

Anyways, can you place the device in Safe mode?

**Comment by rhyde** [comment]
Not sure how to do that.  It is stuck solid magenta

**Comment by kennethlimcp** [comment]
https://docs.particle.io/guide/getting-started/modes/photon/#safe-mode

**Comment by kennethlimcp** [comment]
@rhyde looking at it again, you did not specify a deviceID which is the reason why it failed. 

https://github.com/spark/particle-cli#particle-keys-send

Closing this :)
