### ISSUE TITLE
Document System.set

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/docs#249]
`HAL_Set_System_Config` and `System.set` are not documented yet. I had to dig through the firmware source code to find out how to set the prefix for the SoftAP SSID.

`System.set(SYSTEM_CONFIG_SOFTAP_PREFIX, "Gizmo");`

**Comment by kennethlimcp** [comment]
Firmware reference here: https://github.com/spark/firmware/blob/aefb3342ed50314e502fc792f673af7a74f536f9/hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.cpp#L326
