### ISSUE TITLE
Firmware docs 0.4.9

### ISSUE THREAD

**Issue by m-mcgowan** [particle-iot/docs#267]
Threading
- [x] - delay()/Particle.process() now required in app loop to process app messages
- [x] - Critical section primitives
- [x] - non-blocking listen mode and OTA

General
- [x] - system events
- [x] - Serial.availableForWrite()/Serial.blockOnOverflow() functions
- [x] - attachInterrupt() configurable priority
- [x] - version comment on alaogWrite(DAC)  0.4.6-0.4.7 - pinMode() only required once from 0.4.9 onwards.

**Comment by monkbroc** [comment]
All done!
