### ISSUE TITLE
Searching for "CAN" doesn't display any results

### ISSUE THREAD

**Issue by m-mcgowan** [particle-iot/docs#270]
With the 0.4.9 docs, we added a CAN section. 

Searching for CAN doesn't show any results. Searching for "CAN b" shows "CAN". 

Other TLAs, like "SPI", and "I2C" seem to work as expected, so it's just CAN that the docs can't.

**Comment by technobly** [comment]
My guess was CAN is probably is in some basic word filter list, to avoid generating too many results.  As a stopgap, I added the heading CAN (CANbus) so users can at least search for CANbus and find it.
