### ISSUE TITLE
Firmware docs v0.4.8-rc.6 (Electron)

### ISSUE THREAD

**Issue by m-mcgowan** [particle-iot/docs#271]
v0.4.8-rc.6 MFG Release
- [x] Cellular API [BW]
- [x] PMIC [BW] [stubbed out, opting not to fill this all out completely for now]
- [ ] PMIC [BW] add notes to [setChargeVoltage](https://docs.particle.io/reference/firmware/electron/#setchargevoltage-) to explain what the default charge termination voltage is, and why it's set a bit low.  This is for safety in case charging in higher temps, and can be altered to one higher termination voltage if the user expects the device to operate in a controlled environment.  Document arguments to this function with examples.
- [x] Fuel guage [BW] [stubbed out, added two most commonly used functions, opting not to fill this all out completely]
- [x] PWM pins [BW]
- [x] DAC [BW]
- [x] SPI3 [BW]
- [x] Serial1/2/4/5 [BW]
- [x] CAN [BW]
- [ ] Local build documentation [MDMA 1]

v0.5.0
- [x] <s>Sleep (STOP MODE) will not power off the modem, unlike Photon/P1/Core.</s> This will be replaced with a new API were a user can decide to not turn off the network (NETWORK_STANDBY) when going to sleep.
- [x] Cellular.localIP()

**Comment by technobly** [comment]
Make sure these get updated...
<s>`The Photon and Electron support true analog output`

`The Photon and Electron support communicating with CAN devices via the CAN bus.`</s> **DONE!**

**Comment by technobly** [comment]
Added a new requirement above:
`PMIC [BW] add notes to setChargeVoltage`

**Comment by technobly** [comment]
Updated Sleep Stop mode item for 0.5.x 

> This will be replaced with a new API were a user can decide to not turn off the network when going to sleep (NETWORK_STANDBY).

**Comment by monkbroc** [comment]
Opened a new issue and closing this one
https://github.com/spark/docs/issues/584
