### ISSUE TITLE
update device_claims ref to indicate variable claim_code size

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#272]
says 64 bytes, is often 63, could change.  Should we say 63-128 bytes?

**Comment by monkbroc** [comment]
https://docs.particle.io/reference/api/#create-a-claim-code doesn't show a number of bytes for the claim code. Can I close this?

**Comment by monkbroc** [comment]
I meant to write a comment instead of hitting close. If you think it should be reopened just click the Reopen button please.
