### ISSUE TITLE
Curl command for pre-compiled binary is not correct

### ISSUE THREAD

**Issue by bkobkobko** [particle-iot/docs#278]
In this area:
https://docs.particle.io/reference/api/#flash-a-device-with-a-pre-compiled-binary

The command given to send a pre-compiled bin file over-the-air to a device is not correct.  In particular the -F option does not work with the access_token.  You either have add the token to the URL or use the `-H "Authorization: Bearer 1234"`.  Somehow the doc for this command was changed from the old version where the token was sent in the URL.

I was not able to quickly find this part of the doc sources so someone more familiar with the structure will have to make the edit.

**Comment by kennethlimcp** [comment]
@bkobkobko we do not have access to this change since it's in another private repo so someone from Particle will need to take care of this

**Comment by BracWebb** [comment]
can someone post a correct example of this command here for the time being until the docs are fixed? thanks!

**Comment by BracWebb** [comment]
nm, got it :) for reference:

```
curl -XPUT -F file=@my-firmware-app.bin -F file_type=binary https://api.particle.io/v1/devices/0123456789abcdef01234567?access_token=1234`
```

**Comment by monkbroc** [comment]
I'm cleaning up old issues. I fixed this one a little while back.
