### ISSUE TITLE
Docs search broken in production

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/docs#289]
The search opens URLS without hash so you get https://docs.particle.io/reference/firmware/electron/sleep-sleep- instead of https://docs.particle.io/reference/firmware/electron/#sleep-sleep-

This is the result of clicking on any search result in the docs today:
![image](https://cloud.githubusercontent.com/assets/1919681/13027896/768f4532-d22d-11e5-805d-afb0c48eceb4.png)

Probably due to 4bf4cd2087274350b2436afd1108b49562405660 which uses a lunr fork with this commit https://github.com/spark/metalsmith-lunr/commit/0ec69a139c5a93b8362774068f15d98c9b2b4097

**Comment by m-mcgowan** [comment]
I've reverted that commit and tested locally, with both h1 and h2 links, and the result seems good, so bumped metalsmith-lunr to 0.2.3 and added this as a dependency to the docs module.

**Comment by monkbroc** [comment]
Thanks for the quick fix Mat!
