### ISSUE TITLE
common LED Codes links?

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#291]
Could we link the LED error codes to their respective troubleshooting guides?

https://docs.particle.io/support/troubleshooting/troubleshooting-support/photon/#error-codes

**Comment by wgbartley** [comment]
Might this also cover the SOS codes?

https://docs.particle.io/guide/getting-started/modes/core/#red-flash-sos

**Comment by jenesaisdiq** [comment]
Yeah, it'd be great if someone could write out the common causes of SOS codes. I can look up what they are, but don't really know how to fix them.

**Comment by wgbartley** [comment]
Direct link for reference -- https://docs.particle.io/guide/getting-started/modes/photon/#red-flash-sos

My favorite part is when a device will power on, flash an SOS code, restart, and then work normally all before even connecting to the cloud (which makes me think it's not user code).  Pretty confusing, so some extra descriptions and/or possible troubleshooting steps would be super helpful

**Comment by rickkas7** [comment]
There's a new consolidated reference for LED codes, with content moved from the getting started guide and the old troubleshooting page and cross-referenced.

https://docs.particle.io/reference/led

I also added some troubleshooting tips from in this PR:

https://github.com/particle-iot/docs/pull/810
