### ISSUE TITLE
Wrong version in doc "Common Issue"

### ISSUE THREAD

**Issue by faquin** [particle-iot/docs#293]
The document related to Common Issue mentions the following lines:

Flash part1: dfu-util -d 2b04:d006 -a 0 -s 0x8020000 -D system-part1-**0.4.6**-photon.bin
Flash part2, unit should still be blinking yellow: dfu-util -d 2b04:d006 -a 0 -s 0x8060000:leave -D system-part2-**0.4.6**-photon.bin

0.4.6 is not more a version you would want to flash to your firmware, and it can cause confusion to new users. As example see this thread https://community.particle.io/t/after-load-new-firmware-0-4-6-system-will-not-coming-up/20146

=> Suggest to make this more generic, or to mention that "0.4.6 must be replaced by the target version"
https://github.com/spark/docs/blob/master/src/content/support/troubleshooting/common-issues.md

**Comment by kennethlimcp** [comment]
@faquin, agree. Fixed here: https://github.com/spark/docs/commit/182bf4642c8e3994de02910ef5f6f831b9f03680. 

Thanks!
