### ISSUE TITLE
Table in System Events should flow with smaller windows

### ISSUE THREAD

**Issue by towynlin** [particle-iot/docs#297]
On my mac laptop with a chrome window taking up almost the entire screen, the table in the [system events section of the firmware reference](https://docs.particle.io/reference/firmware/electron/#system-events) gets cut off. All the content is mostly there — it's just that it seems visually cut off without some margin/padding.

![screen shot 2016-02-19 at 1 17 01 pm](https://cloud.githubusercontent.com/assets/3389/13189301/647b73ba-d70b-11e5-9985-f910eafde13f.png)

**Comment by monkbroc** [comment]
This is fixed now.
