### ISSUE TITLE
number of var/func is out dated

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#304]
It's stated here:

```
Currently the application supports the creation of up to 4 different cloud functions.
```

https://docs.particle.io/reference/firmware/electron/#particle-function-

But the thread says:

```
the 0.4.x firmware supports an unbounded number of functions and variables. 
```

http://community.particle.io/t/can-you-change-how-many-web-functions-variables-you-can-register/20635/6

**Comment by hkmoca** [comment]
I've made the change of this issue in this pull request:

https://github.com/spark/docs/pull/324
