### ISSUE TITLE
Blink LED over the internet example

### ISSUE THREAD

**Issue by joegoggins** [particle-iot/docs#31]
Hey @cmsunu28 , 

While I was annotating the firmware examples so they could be imported into the web IDE programmatically, i noticed that the last firmware example uses D0 and D1 for LED pins.  I was thinking it might be better if it used D7 for one of the pins so that the example would show something visible even without doing any wiring.

**Comment by kennethlimcp** [comment]
@joegoggins i checked that the example is using `int led2 = D7;` so closing this :)

https://github.com/spark/docs/blob/master/src/content/en/shared/examples.md#blink-an-led

**Comment by joegoggins** [comment]
You da man @kennethlimcp , thanks for noticing + closing this!
