### ISSUE TITLE
Document curl example for GET /v1/access_tokens

### ISSUE THREAD

**Issue by embedded-creations** [particle-iot/docs#315]
After much searching of the community I found the URL is: `curl https://api.spark.io/v1/access_tokens -u username:password`

I tried to quickly add this to the source for https://docs.particle.io/reference/api/#list-access-tokens but found the "edit" button goes to api.md which doesn't contain a list access tokens section, it instead might be in api_old.md.  The edit got too complicated and was taking too much time.

**Comment by monkbroc** [comment]
Closing old issues. This is now documented.
