### ISSUE TITLE
Please add documentation that you cannot initialize UDP until after you call Cellular.connect()

### ISSUE THREAD

**Issue by hwestbrook** [particle-iot/docs#321]
I wasted some pretty good time today trying to diagnose an issue with UDP and Cellular.connect(). Basically you cannot call Udp.begin() until AFTER you are connected to the network. 

This seems like a no-brainer, but was not obvious to me, so I wasted a bit of time dealing with the issue. If you could add a little snippet to Udp.begin documentation saying to make sure the internet is connected before calling, I think the documentation may be a little friendlier.

**Comment by rickkas7** [comment]
Done. Added note and example code via: https://github.com/particle-iot/docs/pull/814
