### ISSUE TITLE
Clean-up Recommended Operating Conditions Table on Electron Datasheet

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/docs#325]
``` text
Operating Current (Cellular ON, w/powersave)    IIN avg     50  80[4]   mA
Operating Current (Cellular OFF)    IIN avg     2   15  mA
```

https://docs.particle.io/datasheets/electron-datasheet/#recommended-operating-conditions-i-class-icon-check-i-

**Comment by technobly** [comment]
- [x] I believe `Operating Current (Cellular ON, w/powersave)   IIN avg     50  80[4]   mA` is residual from the Photon datasheet.  There is a low power mode of the Electron, but it is not enabled yet and is not called "powersave"... and is also not 50/80mA.
- [x] There are notes 3 - 4 that are missing from this table.

cc: @mohitbhoite

**Comment by ScruffR** [comment]
Note 2 is also missing

**Comment by technobly** [comment]
Updated in Electron Datasheet v002: https://docs.particle.io/datasheets/electron-datasheet/#absolute-maximum-ratings-sup-1-sup-i-class-icon-attention-i-
