### ISSUE TITLE
Electron Interrupt Pin Documentation Missing

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#329]
The same pins on the Photon will work on the Electron, except for D7 which is restricted to use for an internal interrupt (low battery and PMIC).  The other exceptions are that the B0-B5 and C0-C5 pins are currently undocumented... so if they use those, they may interfere with some D0-D6, A0-A7, etc..

**Comment by gramss** [comment]
what about PB12 ?

**Comment by perotom** [comment]
Is there any plan to add the docs soon?

**Comment by ScruffR** [comment]
This is somehow overdue

**Comment by ScruffR** [comment]
Is MODE on the Electron also on PC7? It's not documented in the pin mapping datasheet nor with the `attachInterrupt()`.

**Comment by technobly** [comment]
Yes MODE/SETUP is PC7, also defined as BTN `digitalRead(BTN);`. For reference:
https://docs.particle.io/assets/images/p1-pinout.pdf

**Comment by ScruffR** [comment]
That's the P1 pinout, and it's not really obvious that this should apply for the Electron as is too.

**Comment by technobly** [comment]
Understood. The Photon, P1 and Electron all use the same MCU and were designed to be as pin compatible as possible. I'm leaving the P1 pinout here as an example of what's missing from the Electron pinout.

**Comment by rickkas7** [comment]
Fixed via: https://github.com/particle-iot/docs/pull/827
