### ISSUE TITLE
Authentication docs has old date

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/docs#332]
https://docs.particle.io/guide/how-to-build-a-product/authentication/

> Soon (Late August 2015) you will be able to go to the Particle dashboard and click “Create app” to create a client ID and secret. (Ping @zachary in the forum if we fall behind on this estimate or you just want to say how much you want this feature!)

Let's update that statement.

**Comment by hkmoca** [comment]
i'm on that section, what should it say now?

**Comment by hkmoca** [comment]
will be good to change just the year? or the month as well?

**Comment by monkbroc** [comment]
This feature is now live!
