### ISSUE TITLE
Docs reference non-existing WiFi.status()

### ISSUE THREAD

**Issue by wgbartley** [particle-iot/docs#34]
http://docs.particle.io/photon/firmware/#system-spark-sleep refers to a "WiFi.status()", yet there isn't any documentation for it in the "WiFi" section (http://docs.particle.io/core/firmware/#wifi).  I can't find "WiFi.status()" in the firmware either.

**Comment by kennethlimcp** [comment]
Thanks @wgbartley, removed the description so send some :beers: my way!
