### ISSUE TITLE
"Getting Started" hamburger menu disappears in other sections of "The Guide"

### ISSUE THREAD

**Issue by brandoaire** [particle-iot/docs#345]
If you are not in the "Getting Started" section of the Guide, and navigate to the "Tools and Features" or "How to Build a Product" sections of the Guide, the "Getting Started" navigation items disappear. 

You can view this issue by comparing the nav menu between the following URLs:

https://docs.particle.io/guide/getting-started/intro/electron/
vs. 
https://docs.particle.io/guide/tools-and-features/intro/

![screenshot 2016-04-02 20 37 35](https://cloud.githubusercontent.com/assets/4020511/14230569/c0ad7ae2-f912-11e5-8b87-2754106fa393.png)
vs.
![screenshot 2016-04-02 20 37 10](https://cloud.githubusercontent.com/assets/4020511/14230565/af6f04d0-f912-11e5-9e0c-ff89e9e211f1.png)

**Comment by monkbroc** [comment]
> Hamburger disappears

![image](https://cloud.githubusercontent.com/assets/1919681/14615134/42a5afae-0572-11e6-8a0b-2b10974a814c.png)
