### ISSUE TITLE
Document https://api.particle.io rate limits and make recommendations on how to avoid them

### ISSUE THREAD

**Issue by joegoggins** [particle-iot/docs#348]
A non-trivial portion of https traffic to https://api.particle.io is due to malfunctioning programs in infinite loops. The cause of failure in most of these client programs appears mostly due to failed access tokens and over use of polling instead of pub/sub to interact with a device.

We should document what the hard and software rate limits are and make app development recommendations for how to avoid hitting the limits.

The current ballpark rate limit is around 10 requests per second for a given unique IP address.

**Comment by dmiddlecamp** [comment]
👍

**Comment by rickkas7** [comment]
Done via https://github.com/particle-iot/docs/pull/804
