### ISSUE TITLE
Updates for V0.4.0 firmware

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#35]
- [X] [getPinMode(pin)] https://github.com/spark/docs/pull/261 (tested with bugs)
- [ ]  [Serial Y modem?] https://github.com/spark/docs/pull/215 (tested with SOS flash)
- [ ] [WiFi.resolve()]
- [X] [WiFi.selectAntenna()]
- [ ] Photon memory map,both main memory and DCT area (dfu alt 1)
- [X] LED change callback
- [x]  [shortened Spark.publish()] https://github.com/spark/docs/pull/285
- [x] [Rename to `System.`]  `Spark.sleep()` and `Spark.deviceID()`
- [x]  [update to use `long seconds` for `System.sleep()`]
- [x] Close `Spark.process()` discussion] https://github.com/spark/docs/pull/242
- [x]  Change `System.bootloader()` to `System.dfu()`
- [x]  Update `WiFi.macAddress(mac)` example:

```
for (int i=0; i<6; i++) {
        if (i) Serial.print(":");
        Serial.print(mac[i], HEX);
      }
```

**Comment by m-mcgowan** [comment]
I couldn't reproduce the bug you mentioned for getPinMode(). https://github.com/spark/firmware/issues/437

**Comment by m-mcgowan** [comment]
WiFi.selectAntenna() is in the docs. So is RGB onChange for the LED change callback. (I can't edit the original post.)
