### ISSUE TITLE
Consolidate documentation of LED patterns

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/docs#350]
Some LED patterns are documented here:
https://docs.particle.io/support/troubleshooting/common-issues/photon/
https://docs.particle.io/guide/getting-started/modes/photon/

Some are not documented:
- Solid magenta: firmware update mode (YMODEM)

Move all LED patterns to a common page (I suggest a new reference page), leaving only a few basic ones in getting started.

**Comment by monkbroc** [comment]
See also #291

**Comment by rickkas7** [comment]
Done via: https://github.com/particle-iot/docs/pull/805
