### ISSUE TITLE
clicking on "Lets make some graphs" sends you to IFTTT documentation

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#371]
goto: https://docs.particle.io/guide/tools-and-features/webhooks/#lets-make-some-graphs
click on anchor for "lets make some graphs"
you wind up here: "https://docs.particle.io/guide/tools-and-features/ifttt/"

**Comment by kennethlimcp** [comment]
Actually, all the anchor links shifted by one position...

**Comment by brycekahle** [comment]
I cannot reproduce this.

**Comment by kennethlimcp** [comment]
Click on the `Lets make some graphs` header in the main docs area and not the side bar.

**Comment by brycekahle** [comment]
Still not reproducing. Can you try in an incognito window? I wonder if you have some cached JavaScript.

**Comment by kennethlimcp** [comment]
i hovered over `Introduction`. See link preview at the bottom left

<img width="1280" alt="screen shot 2016-04-21 at 09 10 51" src="https://cloud.githubusercontent.com/assets/6760914/14695061/063c698c-07a1-11e6-82e3-b1eff273e6a6.png">

**Comment by monkbroc** [comment]
I also cannot reproduce this. Can you clarify @kennethlimcp or @dmiddlecamp?

Is this the anchor in the main docs area you were referring to? It correctly points to itself.
![make some graphs](https://cloud.githubusercontent.com/assets/1919681/14710362/162e0f9c-07a3-11e6-8026-ae5be6f45bb8.png)

**Comment by dmiddlecamp** [comment]
hmm, weird. checking.

**Comment by dmiddlecamp** [comment]
Okay that's super weird, it's back to normal now... Did we re-deploy docs recently?  I don't understand why the link would be broken and now be working again.  I'll try to see if I can reproduce again, but closing this for now.
