### ISSUE TITLE
Update Librato Webhooks Example

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#379]
![particle-chart](https://cloud.githubusercontent.com/assets/833793/14796702/55af411e-0af4-11e6-8e39-bfa6b6f7ae25.png)
![particle-metrics-page](https://cloud.githubusercontent.com/assets/833793/14796704/55b37108-0af4-11e6-90cb-bb8ed9022ea7.png)
![librato-getting-started](https://cloud.githubusercontent.com/assets/833793/14796703/55b2fa20-0af4-11e6-8351-927a6fe9199b.png)

```
The new workflow doesn't actually take users to the metric list any more but to an empty workspace. It's really quick to add a chart to the space. This KB article has a video that describes the flow: http://support.metrics.librato.com/knowledgebase/articles/61566-librato-getting-started

```

**Comment by monkbroc** [comment]
This is fixed by #557
