### ISSUE TITLE
Document led_update_handler

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#38]
From: https://community.particle.io/t/best-way-to-implement-an-outboard-bright-rgb-led/12063/2

```
void led_update_handler(void* data, uint8_t r, uint8_t g, uint8_t b, void* reserved)
{
    analogWrite(A0, r);
    analogWrite(A1, g);
    analogWrite(A2, b);
}

void setup()
{
    set_rgb_led_change_handler(led_update_handler, NULL);    
}
```

**Comment by technobly** [comment]
It doesn't work that way anymore, and currently WILL work with this PR: https://github.com/spark/firmware/pull/465 but it's likely going to change going forward.  That said, it seemed appropriate to add some info here :)

**Comment by m-mcgowan** [comment]
This is looking good :+1:  The data pointer just needs storing alongside the callback function and then passed as the first parameter when the callback is called.

I'm puzzled what happened to my original implementation of `set_rgb_led_change_handler()` since this was definitely implemented at some point. Did the gremlins swallow it? :-)

**Comment by technobly** [comment]
I dunno man... I was wondering that myself.  Couldn't find the implementation after like Sept 2014 IIRC.

**Comment by kennethlimcp** [comment]
@m-mcgowan, can you tell me if the above code is good to go? Then i will figure out where it goes

**Comment by pkourany** [comment]
@kennethlimcp, one member and @bkobkobko tested the code and it is NOT working it seems.

https://community.particle.io/t/can-i-start-mirroring-the-led-color-to-my-own-led/15417/13

**Comment by bkobkobko** [comment]
I have to retract my statement--I was trying to use D7 with LED and analogWrite() and those two don't play nice together.

**Comment by pkourany** [comment]
@bkobkobko, the member still has issues with the LEDs nonetheless.

**Comment by kennethlimcp** [comment]
by @wgbartley : https://community.particle.io/t/can-i-start-mirroring-the-led-color-to-my-own-led/15417/17

```
void ledChangeHandler(uint8_t r, uint8_t g, uint8_t b) {

}

void setup() {
    RGB.onChange(ledChangeHandler);
}
```

**Comment by technobly** [comment]
Documented here:
https://docs.particle.io/reference/firmware/photon/#onchange-handler-
