### ISSUE TITLE
Page crashing mobile safari when opening menu

### ISSUE THREAD

**Issue by moors7** [particle-iot/docs#382]
When trying to open the menu on the reference section, the page will crash when in portrait mode but not when in landscape mode. Running on an iPhone 6+ iOS 9.0.2.
![image](https://cloud.githubusercontent.com/assets/6599791/14891661/d29fdb00-0d67-11e6-9c7b-13e00b5072a3.png)

**Comment by monkbroc** [comment]
What browser are you using?

**Comment by moors7** [comment]
Initially, mobile safari (the stock app). But I've just tried, and experienced, the same with Chrome, Firefox, and Opera mini. The latter actually crashes the entire app (back to the home screen) rather than 'only' the page, like the others. Furthermore, the menu does work in landscape mode, on all these browsers.
