### ISSUE TITLE
Power Shield Fuel Gauge Pins

### ISSUE THREAD

**Issue by ericmillsio** [particle-iot/docs#385]
There is no mention that Pins D0 and D1 are connected to the fuel gauge SDA and SCI, respectively. Am I correct that I shouldn't be connecting external components to these pins with the power shield? My LEDs I had connected in DEEP SLEEP MODE had a low intensity glow to them...

**Comment by rickkas7** [comment]
Fixed via https://github.com/particle-iot/docs/pull/828
