### ISSUE TITLE
fw: ADC default sample time

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#394]
From: https://community.particle.io/t/3-questions-from-a-newbie/22675

Is this correct for Photon/Electron?

https://github.com/spark/firmware/blob/9a99ba61c7b6399ccdf8a1238d05803beb7bd1ee/hal/src/stm32f2xx/adc_hal.c#L38

For Core:

https://github.com/spark/firmware/blob/9a99ba61c7b6399ccdf8a1238d05803beb7bd1ee/hal/src/core/adc_hal.c#L38

**Comment by monkbroc** [comment]
Those docs could be improved. I don't know what 480 cycles correspond to in time.

**Comment by rickkas7** [comment]
Fixed via: https://github.com/particle-iot/docs/pull/828
