### ISSUE TITLE
The dfu-util section for Electon is blank

### ISSUE THREAD

**Issue by bkobkobko** [particle-iot/docs#400]
The Electron has a different device ID from the Photon etc. so the dfu-util command is slightly different but a user in the forum got confused trying to use the Photon command on an Electron.

**Comment by monkbroc** [comment]
Where would you expect the dfu-util to be described for the Electron, Brian?

**Comment by bkobkobko** [comment]
The empty section is here:

https://docs.particle.io/support/troubleshooting/troubleshooting-tools/electron/#dfu-commands

If you change the pull-down to Photon, you will see that section appear with the correct USB IDs and addresses for dfu-util.

**Comment by rickkas7** [comment]
The docs had already been updated to add the missing electron dfu-util commands.
