### ISSUE TITLE
Add fastclick to remove 300ms click delay on iOS

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/docs#403]
When using the docs on iOS there is a 300ms delay between tap and action. Add https://github.com/ftlabs/fastclick to make the interactions smoother.

Thanks @moors7 for the recommendation.

**Comment by brycekahle** [comment]
This is no longer necessary if you include `<meta name="viewport" content="width=device-width, initial-scale=1">` and

```
html {
    -ms-touch-action: manipulation;
    touch-action: manipulation;
}
```

https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away
https://webkit.org/blog/5610/more-responsive-tapping-on-ios/

**Comment by moors7** [comment]
Adding the fastclick shouldn't hurt, though I'm totally cool with the native options, provided they work :)!
Adding that bit of CSS should be worthwhile trying.

**Comment by brycekahle** [comment]
Fastclick prevents any kind of zooming.

**Comment by moors7** [comment]
Doesn't `user-scalable=no` do the same (current setup)? I can't seem to scroll currently. But like I said, the native options are fine by me, give it a shot if you haven't already done so?

**Comment by brycekahle** [comment]
Yes it does. We should probably turn that off. I dislike when a page does not allow me to zoom.

**Comment by monkbroc** [comment]
I agree with removing the zoom lock
