### ISSUE TITLE
Electron State of Charge (SoC) never reaches 100%

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#408]
**Issue:**

getSoC() will never report 100% by default
https://docs.particle.io/reference/firmware/electron/#getsoc-

**Reason:**

https://docs.particle.io/reference/firmware/electron/#setchargevoltage-
The default charge termination voltage is set to 4.112V for battery safety when exposing the battery to extended temperatures.

⚠️ If you are positive you are not operating your Electron above 45°C, or wish to assume all risk with modifying this setting, you can get closer to or achieve 100% by setting the charge termination voltage to 4.208V.

**Comment by rickkas7** [comment]
Fixed via: https://github.com/particle-iot/docs/pull/809
