### ISSUE TITLE
Particle.publish() optional data encoding clarification

### ISSUE THREAD

**Issue by wvdv2002** [particle-iot/docs#409]
Could you give some extra information on the optional data you can include from particle.publish? Can I use the whole char range (0-127) or should I base64 encode the data before publishing? Or is it maybe already base64 encoded before sending?

**Comment by monkbroc** [comment]
Particle.publish expects an ASCII string, so any char from 1 to 255 is OK. If you want to send binary data it is a good idea to base64 encode it.
