### ISSUE TITLE
Should firmware headings follow syntax?

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#41]
Looking at `WIFI.CLEARCREDENTIALS()` and `WIFI.HASCREDENTIALS()` that does not have a syntax example on the right, it takes a while and a more experienced person to figure out the syntax.

I will be sending in a PR to add the syntax example but this might be the way to go.

Thoughts? @technobly @cmsunu28 @spark/spark-elite-read-write

**Comment by towynlin** [comment]
Front-end folks should make the design call whether to stick with all caps headings or not. @jme783 @jenesaisdiq 

Either way, we need to always include a code syntax example to show the capitalization. Thank you @kennethlimcp for adding the code block of syntax examples for these two.

**Comment by steelydev** [comment]
IMHO headings should NOT be all caps and should, instead, reflect valid syntax.

**Comment by dmiddlecamp** [comment]
I will say I was bitten by this recently when copy pasting in some func from the docs

**Comment by jenesaisdiq** [comment]
What's the current state of this? Looks to me like docs now have camelCase examples, and that the compile service, at least, is agreeing that camelCase is the correct format (and that ALLCAPS is not).

What'd ya get bitten by, @dmiddlecamp?

**Comment by technobly** [comment]
![screen shot 2015-06-16 at 10 11 17 pm](https://cloud.githubusercontent.com/assets/2249224/8199040/b56496c6-1474-11e5-8a97-a85840216b79.png)
Center column @jenesaisdiq headings are all caps... I agree these should be proper syntax, or if not... do not show the heading as code syntax.  For example: WiFi.clearCredentials() is better than WI-FI CLEAR CREDENTIALS is better than WIFI.CLEARCREDENTIALS()

**Comment by andyw-lala** [comment]
Also, if method returns non-void, strive to provide pseudo-code in the RHS
to indicate useful interpretation of return code.

On Tue, Jun 16, 2015 at 10:18 PM, Technobly notifications@github.com
wrote:

> [image: screen shot 2015-06-16 at 10 11 17 pm]
> https://cloud.githubusercontent.com/assets/2249224/8199040/b56496c6-1474-11e5-8a97-a85840216b79.png
> Center column @jenesaisdiq https://github.com/jenesaisdiq headings are
> all caps... I agree these should be proper syntax, or if not... do not show
> the heading as code syntax. For example: WiFi.clearCredentials() is better
> than WI-FI CLEAR CREDENTIALS is better than WIFI.CLEARCREDENTIALS()
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spark/docs/issues/41#issuecomment-112635825.

## 

Andy

**Comment by jenesaisdiq** [comment]
Ahh, starin' me in the face, thanks @technobly. Will make sure it gets addressed.

Good point @andyw-lala; clearCredentials doesn't especially seem like it needs to have that response caught (for it to be useful), but hasCredentials probably does. I'm not seeing compile errors when I don't assign that return to anything, so it seems that a practical example's the necessary bit.

**Comment by andyw-lala** [comment]
C doesn't complain if you ignore return values, but from a documentation
standpoint, if the function returns useful values, and the descriptive text
explains them, then the example should match.

On Tue, Jun 16, 2015 at 10:38 PM, Richard Whitney notifications@github.com
wrote:

> Ahh, starin' me in the face, thanks @technobly
> https://github.com/technobly. Will make sure it gets addressed.
> 
> Good point @andyw-lala https://github.com/andyw-lala; clearCredentials
> doesn't especially seem like it needs to have that response caught (for it
> to be useful), but hasCredentials probably does. I'm not seeing compile
> errors when I don't assign that return to anything, so it seems that a
> practical example's the necessary bit.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spark/docs/issues/41#issuecomment-112641669.

## 

Andy
