### ISSUE TITLE
read_as_string() does not exist

### ISSUE THREAD

**Issue by WebDust21** [particle-iot/docs#426]
// EXAMPLE from Particle Reference on the SoftAP setup

if (body->bytes_left) {
    char\* data = body->**_read_as_string_**();
    // handle the body data
     dostuff(data);
     // free the data! IMPORTANT!
     free(data);
}

Dug into the source code, and found that that should be "fetch_as_string"; that compiles with no problem.

**Comment by monkbroc** [comment]
Thanks!
