### ISSUE TITLE
Minor formatting issue in web IDE guide

### ISSUE THREAD

**Issue by osmithy** [particle-iot/docs#431]
In https://docs.particle.io/guide/getting-started/build/photon/#web-ide the formatting for the bullets about the Flash, Verify, and Save buttons is broken. Oddly, the actual markdown itself looks correct, so I'm not sure why it's displaying wrong. See https://pbs.twimg.com/media/ClmCMyGUgAE-2Oq.jpg

**Comment by monkbroc** [comment]
Fixed in https://github.com/spark/docs/commit/51f42a0f3b7934b59b5c5fbc55f48cb4fb55b3ab
