### ISSUE TITLE
"setup mode" used in system events but not defined

### ISSUE THREAD

**Issue by embedded-creations** [particle-iot/docs#434]
"setup mode" is used a few times in the [system events](https://docs.particle.io/reference/firmware/electron/#system-events-reference) section, but I couldn't figure out what was meant as there's no mention of "setup mode" in other parts of the docs

As best as I can tell this might be a new name for "listening mode".  You should probably add a note about the multiple names in the above section, or in [Device Modes](https://docs.particle.io/guide/getting-started/modes/electron/) to avoid confusion.

**Comment by rickkas7** [comment]
Fixed via: https://github.com/particle-iot/docs/pull/816
