### ISSUE TITLE
[Electron] Add note about 3rd-Party SIM PINs not being supported currently

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#435]
Currently 3rd-party SIM PIN's "1234, 0000, etc." are not supported and will cause the Electron to blink Blue.  When this happens, logs will indicate:

```
1.617 AT send      10 "AT+CPIN?\r\n"
1.631 AT read  +   18 "\r\n+CPIN: SIM PIN\r\n"
```

Untested, but you may be able to reset your PIN to null with:

```
// replace 0000 with your current pin
Cellular.command("AT+CPIN=\"0000\",\"\"");
```

**Comment by monkbroc** [comment]
The note is at https://docs.particle.io/faq/particle-devices/electron-3rdparty-sims/electron/#about-sim-pins
