### ISSUE TITLE
[Electron] SLEEP_MODE_SOFTPOWEROFF to be added to docs

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#439]
https://docs.particle.io/reference/firmware/electron/#sleep-sleep-
Needs an explanation and example for SLEEP_MODE_SOFTPOWEROFF.  This is used just like SLEEP_MODE_DEEP, with the added benefit that it also sleeps the Fuel Gauge.  This is the only way to achieve the lowest quiescent current on the electron, apart from sleeping the Fuel Gauge before calling SLEEP_MODE_DEEP.  This is also the same net result as used in the user-activated Soft Power Down feature when you double-tap the Mode button and the Electron powers down.

**Comment by monkbroc** [comment]
Any reason why SLEEP_MODE_DEEP doesn't sleep the Fuel Gauge automatically?
