### ISSUE TITLE
Add application notes section

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/docs#441]
Application notes would be focused documents describing best practices for topics such as low-power, PCB layout, data persistence.

**Comment by technobly** [comment]
Adding to this, we need a section for best practices with cellular connections.  How long to sleep to maintain a connection, vs. deep sleeping for longer knowing that the connection will be dropped (so disconnect now and just sleep for a long time).  Relate this to power and data consumption.

Link to this App Note from sleep modes docs, and keepAlive() docs... as well as any other pertinent spots in the docs.

**Comment by monkbroc** [comment]
I'm closing issues that are not actionable. If we create an application notes section, it will as part of a larger rework of docs.
