### ISSUE TITLE
org slug not available in console, docs / urls still refer to orgSlug param

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#447]
https://docs.particle.io/reference/api/#remove-team-member
https://docs.particle.io/reference/api/#remove-device-from-product
https://docs.particle.io/reference/api/#create-a-customer---access-token

etc, etc.

Thanks!

**Comment by brycekahle** [comment]
All that is needed is a docs build.

**Comment by brycekahle** [comment]
Fixed.

**Comment by mchsk** [comment]
Hello, I know the issue is closed but what is this org slug?
I went through the docs, unfortunately I do not seem to have found what this term stands for.

It seems you guys migrated your terminology or the architecture :) right?
Please guide me a little. Thank you! 👍

**Comment by dmiddlecamp** [comment]
Hi @mchsk ,

  An "orgSlug" was a url / database friendly simple name for the organization that managed your products.  We removed that property when we simplified the user experience and removed the paywall around the product creator tools.

Thanks!
David
