### ISSUE TITLE
Document reason for "online" / "offline" events

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#476]
This may seem obvious, but there are some subtleties that need to be documented in how these online/offline events for TCP devices (Photon/P1/Core) vs UDP device (Electron) are posted.

Specifically:

The “online” event is posted after an Electron full handshake, or first message received after a restored session (this happens if the UDP device service restarts for some reason).  In most cases it would be due to a full handshake, which occurs after first power up or if the IP address of the electron changes (usually because the cellular data connection was deactivated / reactivated).  Soft resetting the electron, or sleeping (stop-mode/deepsleep) for short periods of time (<23 minutes) result in resumed sessions which don't cause a full handshake to occur.  Electrons currently never post "offline" events.

TCP based devices like the Photon/P1/Core will post "online" events after each handshake with the cloud, which happens every time they connect.  The "offline" event happens after 60 seconds of not receiving a message from the device, which can happen every ~16 seconds when the device pings the cloud keeping the connection alive, or more frequently if the device is publishing data.

Suggested Docs locations to put this information:

https://docs.particle.io/reference/api/#connection-status

https://docs.particle.io/reference/changelog/#-quot-online-vs-offline-quot-

**Comment by rickkas7** [comment]
Completed via: https://github.com/particle-iot/docs/pull/815
