### ISSUE TITLE
Clarify the location of the Photon Serial2 pins in documentation

### ISSUE THREAD

**Issue by rcaudill** [particle-iot/docs#484]
Photon documentation (https://docs.particle.io/reference/firmware/photon/#serial) references RGB Green (TX) and Blue (RX) LED pins but it's unclear where those pins are.

Clarify in documentation that those "pins" are labeled as 28/29 and are actually pads on the bottom of the PCB. See datasheet (https://docs.particle.io/datasheets/photon-datasheet/#recommended-pcb-land-pattern-photon-without-headers-) for diagram.

**Comment by rcaudill** [comment]
I'll work on this issue.

**Comment by monkbroc** [comment]
OK. Thanks.
