### ISSUE TITLE
webhook rate limit docs out of date

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#495]
https://docs.particle.io/guide/tools-and-features/webhooks/#limits

"A webhook will be disabled if the server responds with errors 10 times in a row." 
^^ I don't think this is true anymore, is it?  Webhooks will sleep, not be disabled.

Also this doesn't mention anything about our product creator tiers?

**Comment by monkbroc** [comment]
I changed the text to say "A webhook will sleep if the server responds with errors 10 times in a row."
https://docs.particle.io/reference/webhooks/#error-limits

Do you have details about the product creator tiers?

**Comment by monkbroc** [comment]
Closing old issues. This is now documented
