### ISSUE TITLE
Add documentation for ssh'ing to raspberrypi.local

### ISSUE THREAD

**Issue by nrobinson2000** [particle-iot/docs#503]
Raspberry Pi comes pre-installed with `avahi-daemon`, which means that its IP address is aliased to `hostname.local`.  The default hostname for Raspberry Pi is `raspberrypi`, so users could just ssh into their Pi by doing:
```
ssh pi@raspberrypi.local
```
This way users would not need to use an elaborate method for finding the IP address of their Pi, which would keep changing because it is DHCP and not static.

**Comment by monkbroc** [comment]
That's super nice! I didn't know that. Can you make a pull request and I'll merge it in!

**Comment by technobly** [comment]
It would be pretty sweet if that could update based on whatever you named your Particle-Pi device.  So if I had `pi1` as the name, I could use `ssh pi@pi1.local`

**Comment by rickkas7** [comment]
It appears you can configure it. I just edited /etc/hostname to be pi3 and rebooted and now I can `ssh pi@pi3.local`, at least from the Mac. Neat!

**Comment by technobly** [comment]
Nice @rickkas7 !  Just to clarify my idea, I meant it would be sweet it if could auto-update whenever I renamed my Pi via the Particle API (Web IDE, CLI, curl, etc..).

**Comment by andyw-lala** [comment]
Just change the hostname and restart a few key services and it should just
happen.

**Comment by nrobinson2000** [comment]
I made a pull request @monkbroc.

https://github.com/spark/docs/pull/506

**Comment by monkbroc** [comment]
I merged the PR. Thanks @nrobinson2000!
