### ISSUE TITLE
Documentation for disabling preprocessor

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#51]
Notes:

The preprocessor sometimes needs to be disabled with

``` cpp
#pragma SPARK_NO_PREPROCESSOR
```

at the top of the file in order for valid code to compile successfully, 
but there's currently no published docs for this.

FYI, this is only necessary for .INO files compiled with Spark IDE, Spark CLI or Spark Dev

**Comment by m-mcgowan** [comment]
One common problem is use of classes/structs in function parameters.

```
class ABC
{
   int abc;    
};

void doSomethingWithABC(const ABC& abc)
{ 
}
```

This gives the error:

```
/spark/compile_service/shared/workspace/6_hal_12_0/firmware-privatest.cpp:6:31: error: 'ABC' does not name a type
void doSomethingWithABC(const ABC& abc);
^
/spark/compile_service/shared/workspace/6_hal_12_0/firmware-privatest.cpp:6:36: error: ISO C++ forbids declaration of 'abc' with no type [-fpermissive]
void doSomethingWithABC(const ABC& abc);
^
make[1]: *** [../build/target/user/platform-6test.o] Error 1
make: *** [user] Error 2
```

So when you see `ABC does not name a type` yet you know the type is defined, consider disabling the preprocessor.

(Why does this error? My guess is that the function forward-declarations being created by the preprocessor are put before the class declaration in the resulting cpp file, causing the compiler error due ABC not being a defined type at the point where the forward declarations appear.)

**Comment by suda** [comment]
Added to http://support.particle.io/hc/en-us/articles/204952620 Is this enough? Or should we link to it somewhere else?

**Comment by m-mcgowan** [comment]
That's good! I'm still drawn to having at least a passing mention of the preprocessor in the docs, with a link to that more fuller description.

**Comment by kennethlimcp** [comment]
@chobberoni should this go under a section by itself under references/firmware?

**Comment by chobberoni** [comment]
@kennethlimcp yes!

**Comment by kennethlimcp** [comment]
@chobberoni , here's the initial PR: https://github.com/spark/docs/pull/175

I think it can be better written to explain what's going on. 

@m-mcgowan, would love your comments about the possible change to `#pragma PARTICLE_NO_PREPROCESSOR` compared to the current `#pragma SPARK_NO_PREPROCESSOR`

Thanks all!

**Comment by m-mcgowan** [comment]
I've no problem adding PARTICLE_NO_PREPROCESSOR so long as the existing pragma is maintained but perhaps accompanied with a deprecation warning.  Since the compiler and firmware are often seen as being part of the same system (you can't really use one without the other when you cloud compile) then I suggest that deprecation of SPARK names follow the API deprecation schedule set out for firmware here - https://github.com/spark/firmware/issues/421#issuecomment-133950921

**Comment by kennethlimcp** [comment]
:+1: this should be part of the migration plan :)

**Comment by technobly** [comment]
Closing since this is in the Docs now:
https://docs.particle.io/reference/firmware/photon/#preprocessor

**Comment by m-mcgowan** [comment]
I've just read the preprocessor docs at https://docs.particle.io/reference/firmware/photon/#preprocessor and it doesn't mention the pragma to disable it, which was the primary intent of this issue. :-)

**Comment by monkbroc** [comment]
This section contains the following:
> If you are getting unexpected errors when compiling valid code, it could be the preprocessor causing issues in your code. You can disable the preprocessor by adding this pragma line. Be sure to add #include "Particle.h" and the function prototypes to your code.
> ```
> #pragma PARTICLE_NO_PREPROCESSOR
> //
> #pragma SPARK_NO_PREPROCESSOR
> ```

**Comment by m-mcgowan** [comment]
Thank you. It still took me 2 attempts to find it even after reading your reply! It was off the bottom of the screen due to the large example in the first paragraph.
