### ISSUE TITLE
/oauth/token API reference do not list client_id / client_secret as required parameters

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#518]
I think we left it out to keep things simple, and just used "particle/particle", but it looks like this is confusing / and the call fails if these parameters are left out.

**where does this happen?**
https://docs.particle.io/reference/api/#generate-an-access-token
https://docs.particle.io/reference/api/#generate-a-customer-scoped-access-token

**What's missing?**
client_id / client_secret parameters

**Where can I copy these from?**
we list these parameters for other calls, such as - https://docs.particle.io/reference/api/#create-a-customer---client-credentials

**Comment by monkbroc** [comment]
Do you have more details about this? Is "particle/particle" always used in `POST /oauth/token` or are there cases where you'd want to use other values perhaps related to products?

**Comment by brycekahle** [comment]
It says under https://docs.particle.io/reference/api/#generate-an-access-token:
> You must give a valid client ID and password in HTTP Basic Auth. For controlling your own developer account, you can use particle:particle. Otherwise use a valid OAuth Client ID and Secret
