### ISSUE TITLE
Document all JSON options for a product webhook

### ISSUE THREAD

**Issue by wvdv2002** [particle-iot/docs#523]
It would be nice to document all possible JSON options for a product webhook.
I cannot find for example how to set the "Only the device that triggers the webhook should receive its response" option in a Custom JSON to load using the Particle CLI.

**Comment by monkbroc** [comment]
I created a webhook reference page at https://docs.particle.io/reference/webhooks/

Unfortunately the CLI doesn't currently support creating product webhooks. It has to be done in the console.
