### ISSUE TITLE
Confusing node.js install steps

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#54]
@emilyrose,

the command-line stuff is not properly aligned and there seem to be a duplicate set of command.

Can you tell me what should go where for **INSTALLING NODE.JS**?

**Comment by technobly** [comment]
@kennethlimcp the only thing I see about Node.js is this (which is pretty short, but Node.js _is_ arguably pretty easy to install):

> First, make sure you have node.js installed!

Did you mean the CLI itself?

**Comment by kennethlimcp** [comment]
Forgotten to put the reference: http://docs.particle.io/photon/connect/#connecting-your-device-using-osx

Users should not even be typing stuff in the terminal to setup

**Comment by technobly** [comment]
I see the terminal stuff now. No idea what those do or why they are necessary. They may be needed, but I have not had to use them and yes agreed they seem confusing.
