### ISSUE TITLE
Use D7 for "Control LEDs over the 'net"

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#56]
http://docs.particle.io/photon/examples/#control-leds-over-the-net

**Comment by technobly** [comment]
@kennethlimcp do you mean just simplify this example to use D7 so there's no wiring needed at all?  If so, not a bad suggestion :)

**Comment by kennethlimcp** [comment]
We can use D0/D1 + D7 so even if the user did not hooked up an external LED, they can still use follow the example instead of pulling their hair ;)

**Comment by joegoggins** [comment]
Love the suggestion @kennethlimcp, great idea! If you get a moment, go ahead and make this change, then ping me and I'll re-import this example into the Web IDE in a jiffy flash!  (The code that lives in the IDE is now directly extracted from the docs my a script that targets the invisible html markup snippets like `<a data-firmware-example-code-block=true>` and `<a id="variables-with-a-temperature-sensor" data-firmware-example-url="..."`, so it's easy to keep things in sync.)

**Comment by kennethlimcp** [comment]
@joejoggins, after thinking through and looking at the **examples** flow, it makes absolute sense to use **D7** over **D1** since it's the same setup as **Blinking an LED**. 

Please update this for the Web IDE.

Thanks!

Fixed: https://github.com/spark/docs/commit/54161f67ce89c2ff17e3896424839c7d01a39f4f

**Comment by kennethlimcp** [comment]
@joegoggins bump

**Comment by joegoggins** [comment]
Thanks for making this change @kennethlimcp , just updated it in the Web Build IDE.

On a related note, when @cmsunu28 and I saw this change, it prompted a conversation of ways to improve the firmware examples sequence and make the learning on-ramp easier. Christine will be reaching out to you directly about this.
