### ISSUE TITLE
Particle.publish and Particle.subscribe PUBLIC and PRIVATE events are mutually exclusive

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#560]
Missing bit of info to document!

https://docs.particle.io/reference/firmware/electron/#particle-publish-
https://docs.particle.io/reference/firmware/electron/#particle-subscribe-

- Particle.subscribe to a specific device is presently not supported (although you can do this with the CLI)
- Particle.subscribe to MY_DEVICES receive only PRIVATE events. 
- Particle.subscribe to ALL_DEVICES receive only PUBLIC events. 
- Particle.subscribe without any flag "default blank" receives only PUBLIC events. 

| | | Particle.subscribe | Particle.subscribe | Particle.subscribe | Particle.subscribe |
| --: | :-: | :-: | :-: | :-: | :-: |
| | **flags** | ALL_DEVICES | MY_DEVICES | default blank | Specific Device |
| **Particle.publish** | PUBLIC | Y | - | Y | N/A |
| **Particle.publish** | PRIVATE | - | Y | - | N/A |
| **Particle.publish** | default blank | Y | - | Y | N/A |

**Comment by technobly** [comment]
Should also be noted that the CLI behaves a bit differently than the Particle.subscribe() API.

When using `particle subscribe mine` I can see one of my PUBLIC events.  So the CLI must not be subscribing to PRIVATE events per say, but just filtering my events from the public stream?

Is there a way to subscribe to PRIVATE events specifically with the CLI? https://github.com/spark/particle-cli#particle-subscribe

**Comment by monkbroc** [comment]
> subscriptions to a specific device is presently not supported.
Is that true? The code seems to pass the device ID to the HAL then to the cloud.
https://github.com/spark/firmware/blob/develop/wiring/inc/spark_wiring_cloud.h#L251

MY_DEVICES / ALL and public/private are different. More combinations than public / ALL and private MY_DEVICES should work but I can't say for sure.

The CLI is using the API endpoint to subscribe but the firmware is talking to the device service directly. So there may be some differences.

**Comment by technobly** [comment]
Just ran a test with this example code to show the relationship of PUBLIC/PRIVATE events and ALL_DEVICES/MY_DEVICES event stream subscriptions
```c
void myPublicHandler(const char *event, const char *data)
{
    Serial.printlnf("Public Handler: %s,%s", event, data);
}

void myPrivateHandler(const char *event, const char *data)
{
    Serial.printlnf("Private Handler: %s,%s", event, data);
}

void myDefaultHandler(const char *event, const char *data)
{
    Serial.printlnf("Default Handler: %s,%s", event, data);
}

void setup() {
    // only receives PUBLIC events
    Particle.subscribe("bretts-test-public", myPublicHandler, ALL_DEVICES);

    // only receives PRIVATE events
    Particle.subscribe("bretts-test-private", myPrivateHandler, MY_DEVICES); 

    // only receives PUBLIC events
    Particle.subscribe("bretts-test-default", myDefaultHandler);
}
int count = 0;
void loop() {
    Serial.printlnf("Yo: %04d", count++);
    delay(1000);
}
```

**Comment by monkbroc** [comment]
`particle subscribe mine` gets both PUBLIC and PRIVATE, but only from MY_DEVICES.

**Comment by rickkas7** [comment]
Fixed via: https://github.com/particle-iot/docs/pull/817
