### ISSUE TITLE
WiFi.setCredentials() requires WiFi.on in SEMI_AUTOMATIC or MANUAL mode

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#561]
WiFi.setCredentials() requires WiFi.on in SEMI_AUTOMATIC or MANUAL mode.  See discussion here, but know that just documenting this fact will be sufficient.

https://github.com/spark/firmware/issues/881

**Comment by rickkas7** [comment]
The docs had already been edited to add a note about this.
