### ISSUE TITLE
PDF of datasheets

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/docs#563]
Generate pretty PDFs from hardware datasheets markdown.

**Comment by monkbroc** [comment]
See http://chrisanthropic.github.io/Open-Publisher-Documentation/ for inspiration
https://github.com/chrisanthropic/Open-Publisher
https://github.com/chrisanthropic/docker-Open-Publisher-Base

**Comment by monkbroc** [comment]
Other possibilities: wkhtmltopdf, wkpdf, pandoc

**Comment by anatoly-particle** [comment]
Implemented in #693.
