### ISSUE TITLE
Time.format() and other Time functions expect UTC time format

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#574]
- [ ] Add clarification to docs about most Time class functions requiring UTC time format.

- [ ] Add reasoning for Time.local(), and warning not to use it in other Time functions without understanding the consequence.

- [ ] Add shortcut example to Time.format() 
```
Serial.println(Time.format(TIME_FORMAT_ISO8601_FULL));
```

**Comment by rickkas7** [comment]
Done! https://github.com/particle-iot/docs/pull/819
