### ISSUE TITLE
Replace serial waiting example

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/docs#577]
Rework the code that waits for a character to be sent from the device in several of our examples.  That was mainly for Windows machines at the time, but can help for Mac as well.  There is some new code which will wait, not require anything to be sent (so you can use the CLI) and proceed on if you don’t connect serial.
`waitFor(Serial.isConnected, 10000);` waits 10 seconds.  isConnected I believe is in 0.5.3 so should be fairly well adopted by now.

**Comment by rickkas7** [comment]
Completed via: https://github.com/particle-iot/docs/pull/826
