### ISSUE TITLE
Document stack sizes

### ISSUE THREAD

**Issue by towynlin** [particle-iot/docs#579]
Inspired by https://community.particle.io/t/what-are-the-available-stack-sizes/29450

- Normal app on Electron
- Electron with `SYSTEM_THREAD(ENABLED)` (user thread and system thread have their own stacks)
- Additionally on Photon/P1, WICED creates a bunch of threads with their own stacks as well as one for the application with a 6144 byte stack
- `Thread` (undocumented as of Feb 2017) has a default stack size of 3KB

**Comment by rickkas7** [comment]
Done via: https://github.com/particle-iot/docs/pull/811
