### ISSUE TITLE
Create Particle Primitive Guide

### ISSUE THREAD

**Issue by jme783** [particle-iot/docs#595]
I realized today that while we have plenty of reference documentation, our documentation never _introduces_ our core primitive or describes what they should be used for. It would be a great thing to add to the guide.

Things to cover on this page in the guide:
- `Particle.function()`
- `Parcle.variable()`
- `Particle.publish()`
- `Particle.subscribe()`

Specifically, the guide should introduce these concepts as well as describe the conditions in which they should be used.

**Comment by rickkas7** [comment]
Now here:
https://docs.particle.io/tutorials/device-os/device-os/#communication
