### ISSUE TITLE
Some doc pages unusable on mobile Safari an Chrome (crash)

### ISSUE THREAD

**Issue by mjmare** [particle-iot/docs#60]
Some pages, eg http://docs.particle.io/photon/firmware/#wifi-setcredentials, make Safari and Chrome crash. 
I've reported this before, (this is an old problem), I thought a reminder might be useful. 

The pages are fine in the desktop versions of the browsers. Running iOS 8, fully updated.

**Comment by kennethlimcp** [comment]
@mjmare, what's the model for your iPhone?

**Comment by mjmare** [comment]
Hi

iPad Air 2, but had this with the previous model as well (was running iOS 7 perhaps).

Marcel

**Comment by kennethlimcp** [comment]
I believe the images are too huge and we need to downsize them. The entire docs is `~700mb!`

**Comment by kennethlimcp** [comment]
Going to close this since `metal-smith` docs are introduced
