### ISSUE TITLE
Can I get multiple events' data in one 'particle.getEventStream' request? 

### ISSUE THREAD

**Issue by XidongHuang** [particle-iot/docs#606]
Hi, I just start using Particle, and now I am trying to handle those data from Particle server.
So I can get a specific event data with a specific device, the code just like the document sample:
```
programming language: node.js 7.8.0
```
```
...
particle.getEventStream({
    deviceId: deviceId,
    name: 'event1',
    auth: token,
}).then(
    (stream) => {
        stream.on('event', (data) => {
            console.log('Event:', JSON.stringify(data));
        }
    },
    (err) => {
        console.log('Error:', err);
    }
)
...
```
Now, my question is: Could I get multiple events in one request?
like assign an `array` for the `name`?

Thanks

**Comment by rickkas7** [comment]
No, but "name" is a prefix that will match all event names beginning with that. 

So if you register for "event" you can get event1, event2, ...

**Comment by XidongHuang** [comment]
Thanks @rickkas7
