### ISSUE TITLE
Document Particle.publish() PUBLIC flag and Particle.subscribe() ALL_DEVICES flag

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#611]
Currently the default behavior when not specifying a scope flag is:

Particle.publish("foo","bar"); // PUBLIC
Particle.subscribe("foo", myHandler); // ALL_DEVICES

Document that these flags (PUBLIC and ALL_DEVICES) can be explicitly used as well to ensure future code does not change from the desired behavior.

**NOTE: 0.7.0 will be changing the default behavior when no scope flag is specified.**

**Comment by rickkas7** [comment]
Has been documented for a while, closing issue.
