### ISSUE TITLE
curl path in 'Get a Variable Value' example is incorrect

### ISSUE THREAD

**Issue by jonlogan** [particle-iot/docs#620]
Discovered this when attempting a curl command to extract a Variable value.   The page URL is:
https://docs.particle.io/reference/api/#get-a-variable-value

In the righthand panel that shows actual curl code, the sample curl command for extracting a Variable for a device within a Product is incorrect/incomplete.  

It currently says:
$ curl https://api.particle.io/v1/products/:productIdOrSlug/0123456789abcdef01234567/temperature\?access_token\=1234

However, it is missing the /devices path.  The correct syntax should be (added ** for emphasis):
$ curl
https://api.particle.io/v1/products/:productIdOrSlug/**devices/**0123456789abcdef01234567/temperature\?access_token\=1234

Here's a screenshot of the current syntax, which is missing /devices:
![image](https://cloud.githubusercontent.com/assets/12702821/25255579/36a6805e-25e0-11e7-936c-7fa2d005132e.png)

**Comment by jme783** [comment]
This should now be fixed! Thanks @jonlogan for the report
