### ISSUE TITLE
Remove unsigned driver instructions

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#65]
@m-mcgowan ,

please confirm that the instructions can be removed with the release of signed drivers - https://github.com/spark/docs/blob/master/src/content/en/photon/connect.md#installing-the-particle-driver

**Comment by m-mcgowan** [comment]
The Core drivers have always been signed, so I don't think signing the Photon drivers affects the process in any way other than making it work with versions of Windows that insist on signed drivers.

Eventually we may have an installer to install the DFU and Serial drivers to make the process download and click.

**Comment by kennethlimcp** [comment]
So do we need the instructions or do we not with all signed drivers?

**Comment by m-mcgowan** [comment]
We still need instructions. The instructions have little to do with whether the driver is signed or not.
