### ISSUE TITLE
not sure why "get device name" example has a 5 second loop delay

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#655]
here: https://docs.particle.io/reference/firmware/photon/#get-device-name

this code snippet was confusing, not sure how / why it contributed to using this feature?

<img width="523" alt="screen shot 2017-07-12 at 11 02 47 am" src="https://user-images.githubusercontent.com/833793/28127298-a444bca0-66f1-11e7-84b6-0a2512dc4946.png">

edit: should this be updated to "particle" and not "spark" ?

**Comment by monkbroc** [comment]
My guess is that it's because the subscribe is for all `spark/` events so waiting for 5 seconds makes it so you receive only the name event.

I'll try switching to only subscribing to the name event and removing the delay.
