### ISSUE TITLE
docs don't link to bootloader in firmware repo

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#658]
these link to ( https://github.com/rickkas7/particle_jtag/blob/master/files/bootloader-photon.bin?raw=true ) instead of our repo:

https://docs.particle.io/faq/particle-tools/jtag/photon/#programming-the-boot-loader

**Comment by rickkas7** [comment]
Oops, missed that when the FAQ was moved. Will fix.

**Comment by rickkas7** [comment]
Fixed by: https://github.com/spark/docs/pull/659
