### ISSUE TITLE
Installation steps for firmware local build

### ISSUE THREAD

**Issue by monkbroc** [particle-iot/docs#663]
There should be a simple series of steps to install the basic firmware toolchain for people who want to build their firmware locally.

**Comment by rickkas7** [comment]
There's a FAQ, like adding a bullet list summary at the top for people who basically know what they're doing?

https://docs.particle.io/faq/particle-tools/local-build/

**Comment by monkbroc** [comment]
Ah cool. I think this is a discoverability problem. I'll ask the person who asked the question to see where they looked for the info in the docs and plop a link there.

**Comment by monkbroc** [comment]
I added links in the guide section to that FAQ. Thanks!
