### ISSUE TITLE
many references to :orgSlug which is deprecated 

### ISSUE THREAD

**Issue by TechplexEngineer** [particle-iot/docs#676]
Here is one for example:
https://docs.particle.io/guide/how-to-build-a-product/authentication/#4-create-claim-code-amp-send-to-device

> This endpoint is POST /v1/orgs/:orgSlug/products/:productSlug/device_claims. The customer's access token is required, and is used to generate a claim code that will allow for the link between the device and the customer.

https://community.particle.io/t/how-do-i-get-my-orgslug-and-productslug/35143/4

**Comment by monkbroc** [comment]
Thanks! I updated the endpoints to point to the product endpoints.
