### ISSUE TITLE
Arrows for Getting Started broken around step 8

### ISSUE THREAD

**Issue by beriberikix** [particle-iot/docs#679]
Steps to reproduce:

1. Navigate to docs.particle.io/guide/getting-started and make sure "Photon" is selected from device label dropdown
2. Click on "7. Code Examples" from the left nav
3. Click on the right arrow to go to the next section

What did I expect:

Navigate to "https://docs.particle.io/guide/getting-started/contributing/photon/" and the "8. Open Source" section highlighted.

What Happened:

I was redirected to "https://docs.particle.io/guide/getting-started/billing/electron/" and the "8. Electron Billing Guide" was selected. Also, all devices are missing from the device drop down except for "Electron."

There is a similar issues that I believe to be related:

1. Navigate to docs.particle.io/guide/getting-started and make sure "Photon" is selected from device label dropdown
2. Click on "8. Open Source" from the left nav
3. Click on the _left arrow_ to go to the previous section
4. Observe the same result

System details:
Ch 60.0.3112.113, macOS Sierra 10.12.6

**Comment by monkbroc** [comment]
This has annoyed me for a long time. I went ahead and fixed it now that I have a better understand of how the docs generator works. See #680
