### ISSUE TITLE
Is your electron compatible article links to kickstarter for country link

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#687]
what article: 

https://docs.particle.io/support/troubleshooting/common-issues/electron/#1-is-your-electron-compatible-with-your-local-cellular-network-

link text:
    For a detailed list of 3G service country by country, please visit the following link.

link destination:
    https://www.kickstarter.com/projects/sparkdevices/spark-electron-cellular-dev-kit-with-a-simple-data/description

link should go?

  not sure, here? https://www.particle.io/pricing#cellular-data

**Comment by rickkas7** [comment]
Yes, I generally direct to the pricing#cellular-data link, that seems like a good choice here.

**Comment by rickkas7** [comment]
The common issues page no longer exists, and I did a search for "spark-electron-cellular-dev-kit-with-a-simple-data" in the docs and there is no reference to it anywhere else.
