### ISSUE TITLE
Change OS X to macOS

### ISSUE THREAD

**Issue by dwaq** [particle-iot/docs#701]
[Apple has decided to retroactively rename OS X to macOS.](https://apple.stackexchange.com/questions/256088/is-apple-changing-os-x-branding-to-macos-retroactively) The page at [`/src/content/guide/tools-and-features/firmware-manager.md`](https://docs.particle.io/guide/tools-and-features/firmware-manager/photon/) refers to the OS as OS X. I do see that macOS is used at least once on that page though.

The link to the download also uses the old OS name, but I think this should **not** be changed. At least until a new version comes out, so that it doesn't break the link.

Additionally, the logo is outdated. I can't find much information about the new logo. I think it may just be "macOS" typed out in Apple's font.

Technically, this would be a simple change, but hopefully someone from Particle can chime in on what exactly should be changed. Then hopefully someone else can come in and make the changes.

**Comment by jtzemp** [comment]
Also just adding my $0.02 to this. For SEO purposes, I don't think we want to completely eliminate "Mac OS X" from the text, since a lot of people still search using that term. I do think we need to add "macOS" to more places though.

**Comment by rickkas7** [comment]
Completed via:
https://github.com/particle-iot/docs/commit/559eee76e4ec917c5b5cfea4bfebf0b8bda38b9e

In the first use in a page, it's generally written as "macOS (OS X)" and subsequently as macOS.
