### ISSUE TITLE
Incorrect example time given for hourFormat12() reference docs

### ISSUE THREAD

**Issue by aaronverhoeven** [particle-iot/docs#707]
I noticed that the 12-hour time example is said to return '15' which doesn't make any sense. I believe it should say 3, which would be the 12-hour time as opposed to 24 hours time.

If I'm correct, this is a small typo, but could easily confuse people new to the system or trying to implement a 12 vs 24 hour clock system.

<img width="1282" alt="screen shot 2017-11-06 at 11 58 48 pm" src="https://user-images.githubusercontent.com/13070360/32477858-44e91cbe-c34f-11e7-9584-fc40bd0c86c9.png">

Thanks for noting this, and putting so much effort into a fantastic set of Docs for the Particle/Electron system.

**Comment by pkourany** [comment]
@aaronverhoeven, I just committed a change to the docs.  The correct hour (GMT) should be 3, not 15.  Thanks!
