### ISSUE TITLE
Documentation needs to be updated to reflect substitute parts in some of the Kits

### ISSUE THREAD

**Issue by blave** [particle-iot/docs#738]
A "little while ago" (not sure how long, but it's been at least a couple months) the CdS photoresistor in some of the kits was replaced with an RoHS compliant photoTRANSistor. I've had at least three ZenDesk tickets where customers complain that they didn't get the photoresistor as shown in the docs. Both text (including page links) and images need to be updated.

Occurrences (note that I recorded these URLs from the "old" website so some might've changed?):
https://store.particle.io/products/particle-maker-kit
https://store.particle.io/products/photon-kit (picture only)
https://store.particle.io/products/electron-3g-americas and all other Electron kits
https://docs.particle.io/datasheets/kits-and-accessories/particle-shields/#photoresistor-1-
https://docs.particle.io/datasheets/kits-and-accessories/particle-shields/#photoresistors-2-
https://docs.particle.io/datasheets/kits-and-accessories/particle-shields/#electron-sensor-kit
https://docs.particle.io/guide/getting-started/examples/photon/ (several places)
https://docs.particle.io/guide/getting-started/examples/electron/ (several places)

**Comment by rickkas7** [comment]
Done - the documentation now includes instructions for both the phototransistor and photoresistor.
