### ISSUE TITLE
Android guide placeholder, create guide or remove placeholder

### ISSUE THREAD

**Issue by towynlin** [particle-iot/docs#758]
In the "Building your own mobile app" section of the "How to build a product" guide, near the bottom, it says:
> The guide for how to create an Android app for Particle devices in Android studio is coming soon.

This text was written [3 years ago](https://github.com/particle-iot/docs/blame/6b8cfcd642df68cf2cf8673a3ac8b5b6baaf3c60/src/content/guide/how-to-build-a-product/mobile-app.md#L205).

Has it been superseded by other content? If so, point to that content; if not, delete that sentence.

**Comment by rickkas7** [comment]
This whole section of the docs was removed.
