### ISSUE TITLE
Documentation doesn't mention eSeries, still refers to Core

### ISSUE THREAD

**Issue by rdcparticle** [particle-iot/docs#762]
A lot of spots in [this doc series](https://docs.particle.io/guide/how-to-build-a-product/intro/) refer to Spark Core -- is there any reason to keep this in? Or should we do a find+ replace?

Documentation is primarily focused on Wifi products, eSeries isn't mentioned in any of the pages I've found.

A few specific examples:
- https://docs.particle.io/guide/how-to-build-a-product/pcb-design/ - doesn't link to eSeries data sheet
- https://docs.particle.io/guide/how-to-build-a-product/security/ - no mention of eSeries, still lists Core
- https://docs.particle.io/guide/how-to-build-a-product/manufacturing/ - no mention of eSeries, most of the article talks only about "Photo/P0/P1"

**Comment by technobly** [comment]
Double check this, but I’m pretty sure when we made the name change from Spark to Particle that we decided to leave the Core referred to as the Spark Core, and new hardware would be Particle Photon, P1, Electron, etc..

**Comment by technobly** [comment]
More evidence that it should be Spark Core. https://docs.particle.io/support/support-and-fulfillment/faq/#q-where-do-i-buy-this-thing-called-39-spark-core-39-

**Comment by technobly** [comment]
E-Series is mainly found in the datasheet section https://docs.particle.io/datasheets/electron-(cellular)/e-series-datasheet/

**Comment by rdcparticle** [comment]
Apologies, my comments were specifically regarding the "[How to Build a Product](https://docs.particle.io/guide/how-to-build-a-product/intro/)" section -- I should've been more specific.

- for example, the top of section 2 lists the Photon/P-series and links to them, presumably because it was written in the Wifi-only era. If the intention is have all of our products listed, it should be updated to include electron/eSeries, yes?

> ![image](https://user-images.githubusercontent.com/38296226/38705281-e8557d3c-3e5d-11e8-86b2-0442208a0f3e.png)

- Next question -- should we be talking about the Spark Core _at all_ in our documentation anymore? We don't sell it anymore. People who own them already are likely not referring to "getting started" documentation anymore. Should we remove it to avoid noise and user confusion?

**Comment by rickkas7** [comment]
The how to build a product section no longer exists. Also also the Core instructions are still here, but no longer prominently displayed unless you select Core from the device popup.
