### ISSUE TITLE
GET /v1/sims/:iccid missing from API SIM card reference documentation

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#790]
got confused trying to find if "mb_limit" was returned on the sim card info endpoint, and then realized that endpoint wasn't listed.

Should be here-ish : https://docs.particle.io/reference/api/#list-sim-cards

**Comment by monkbroc** [comment]
@andrewrod33 I made you the owner. Can you publish the documentation for this endpoint?

**Comment by andrewrod33** [comment]
@monkbroc Documentation has been published

https://docs.particle.io/reference/api/#get-sim-information
