### ISSUE TITLE
Add Spark.unsubscribe() to the docs

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#80]
https://github.com/spark/firmware/blob/develop/wiring/inc/spark_wiring_cloud.h#L96-L99

**Comment by m-mcgowan** [comment]
This was mainly intended as a test method. I can't really see a use case for it in production since subscriptions tend to be setup for the lifetime of the application. Though I suppose there's no harm in documenting even if it's no use to 99% of developers.

**Comment by kennethlimcp** [comment]
Closing this since it has made it to the docs: https://docs.particle.io/reference/firmware/photon/#spark-unsubscribe-
