### ISSUE TITLE
Switching between Core and Photon gets 404 for some pages.

### ISSUE THREAD

**Issue by mumblepins** [particle-iot/docs#81]
When switching between the Core and Photon docs, the page automagically redirects to the equivalent page, however for some pages, there is no equivalent, so a 404 is returned.  For example, going from Photon Hardware to the Core gets a 404, and when going from Hardware on the Core page to the Photon page, the menu gets stuck on the Core menu.

**Comment by cmsunu28** [comment]
Thanks for this! We're working on a larger fix for the docs that should take care of this issue.

**Comment by kennethlimcp** [comment]
Should be fixed with new metalsmith docs
