### ISSUE TITLE
Document photon memory map

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#82]
It gets uber annoying having to refer to github and search through forum posts to figure out what goes where.

**Comment by technobly** [comment]
_Ok, where should we put this?_

---

## Flash Layout
- Bootloader (16k)
- WICED DCT area (16k), stores wifi creds, certificates, mfr info, system flags etc.
- WICED DCT swap area (16k)
- eeprom emulation bank 1 (16k)
- eeprom emulation bank 2 (64k) [only 16k used]
- system code (512k) [256k wifi/comms + 256k hal/platform/services]
- factory backup, OTA backup and user code (384k) [3 x 128k]

## DFU config for app data

The DCT code has been mapped to a separate DFU media device to that we can incrementally update the application data. The DCT code allows one item (say, server public key) to be updated without erasing the other items.

These are the current offsets (from platform/MCU/STM32Fxx/Spark_Firmware_Driver/inc/dct.h):

#### Version 0.0.3 - release to manufacturing (April 9 2015)

```
STATIC_ASSERT_DCT_OFFSET(system_flags, 0);
STATIC_ASSERT_DCT_OFFSET(version, 32);
STATIC_ASSERT_DCT_OFFSET(device_private_key, 34);
STATIC_ASSERT_DCT_OFFSET(device_public_key, 1250 /*34+1216*/);
STATIC_ASSERT_DCT_OFFSET(unused_server_address, 1634 /* 1250 + 384 */);
STATIC_ASSERT_DCT_OFFSET(claim_code, 1762 /* 1634 + 128 */);
STATIC_ASSERT_DCT_OFFSET(claimed, 1825 /* 1762 + 63 */ );
STATIC_ASSERT_DCT_OFFSET(ssid_prefix, 1826 /* 1825 + 1 */);
STATIC_ASSERT_DCT_OFFSET(device_id, 1852 /* 1826 + 26 */);
STATIC_ASSERT_DCT_OFFSET(version_string, 1858 /* 1852 + 6 */);
STATIC_ASSERT_DCT_OFFSET(reserved1, 1890 /* 1868 + 32 */);
STATIC_ASSERT_DCT_OFFSET(server_public_key, 2082 /* 1890 + 192 */);
STATIC_ASSERT_DCT_OFFSET(padding, 2850 /* 2082 + 768 */);
STATIC_ASSERT_DCT_OFFSET(flash_modules, 2852 /* 2850 + 2 */);
STATIC_ASSERT_DCT_OFFSET(product_store, 2952 /* 2852 + 100 */);
STATIC_ASSERT_DCT_OFFSET(reserved2, 2976 /* 2952 + 24 */);
STATIC_ASSERT_DCT_OFFSET(end, 4258 /* 2952 + 1282 */);


STATIC_ASSERT_FLAGS_OFFSET(Bootloader_Version_SysFlag, 4);
STATIC_ASSERT_FLAGS_OFFSET(NVMEM_SPARK_Reset_SysFlag, 6);
STATIC_ASSERT_FLAGS_OFFSET(FLASH_OTA_Update_SysFlag, 8);
STATIC_ASSERT_FLAGS_OFFSET(OTA_FLASHED_Status_SysFlag, 10);
STATIC_ASSERT_FLAGS_OFFSET(Factory_Reset_SysFlag, 12);
STATIC_ASSERT_FLAGS_OFFSET(IWDG_Enable_SysFlag, 14);
STATIC_ASSERT_FLAGS_OFFSET(dfu_on_no_firmware, 16);
STATIC_ASSERT_FLAGS_OFFSET(Factory_Reset_Done_SysFlag, 17);
STATIC_ASSERT_FLAGS_OFFSET(StartupMode_SysFlag, 18);
STATIC_ASSERT_FLAGS_OFFSET(unused, 19);
STATIC_ASSERT_FLAGS_OFFSET(RCC_CSR_SysFlag, 20);
STATIC_ASSERT_FLAGS_OFFSET(reserved, 24);
```

## Memory Map (Common)

| Region | Start Address | End Address | Size |
| :-- | --- | --- | --- |
| Bootloader | 0x8000000 | 0x8004000 | 16 KB |
| DCT1 | 0x8004000 | 0x8008000 | 16 KB |
| DCT2 | 0x8008000 | 0x800C000 | 16 KB |
| EEPROM1 | 0x800C000 | 0x8010000 | 16 KB |
| EEPROM2 | 0x8010000 | 0x8020000 | 64 KB |

## Memory Map (Modular Firmware - default)

| Region | Start Address | End Address | Size |
| :-- | --- | --- | --- |
| System Part 1 | 0x8020000 | 0x8060000 | 256 KB |
| System Part 2 | 0x8060000 | 0x80A0000 | 256 KB |
| User Part | 0x80A0000 | 0x80C0000 | 128 KB |
| OTA backup | 0x80C0000 | 0x80E0000 | 128 KB |
| Factory backup | 0x80E0000 | 0x8100000 | 128 KB |

## Memory Map (Monolithic Firmware - optional)

| Region | Start Address | End Address | Size |
| :-- | --- | --- | --- |
| Firmware | 0x8020000 | 0x8080000 | 384 KB |
| Factory Reset | 0x8080000 | 0x80E0000 | 384 KB |
| Unused (factory reset modular) | 0x80E0000 | 0x8100000 | 128 KB |

**Comment by kennethlimcp** [comment]
Would be best for memory map of Particle :cloud: keys and user private keys as well.

**Comment by kennethlimcp** [comment]
@m-mcgowan, can you confirm this as per V0.4.5? I will fit it under datasheet/memory map

**Comment by pkourany** [comment]
Is it possible to add the SRAM map showing the VBAT backed area?

**Comment by m-mcgowan** [comment]
If users are using the `retained` modifier that I added, then you don't really need to know where the backup SRAM is, just use it!

The details above are correct, but I wouldn't publish the DCT region in that format - only pick out the critical details, such as device keys, SSID prefix, device_id (which is a 6 character random code.) Plase also mention that writing 0xFF to offset 34 will cause the device to re-generate a new private key.

**Comment by kennethlimcp** [comment]
:+1:

**Comment by m-mcgowan** [comment]
So where can we put this in the docs? For the core, it goes in the datasheet section. since that's not generally editable for the photon we need another section?

**Comment by m-mcgowan** [comment]
It seems we're kinda stuck here - I love to see some forward motion - waiting for the next big datasheet update doesn't feel very agile! ;-)  I think for now I'll add this to the reference section of the Photon docs. 

I realize this is inconsistent with the Core, but at least it gets the information published now and we can re-position it to somewhere more optimal (e.g. the datasheet) when that is ready.

**Comment by towynlin** [comment]
Agreed — we have the memory map in hand and just need to show it to people. We should not make people wait for this.

I'd advocate for adding the memory map to https://docs.particle.io/datasheets/photon-datasheet/ without the rest of the datasheet updates, so that the URL is consistent with the Core. Any reason I'm missing why we can't do that?

Also, make sure searching for "memory map" in the docs retrieves this as a result no matter where it goes.

**Comment by m-mcgowan** [comment]
I was thinking the datasheet was some externally maintained file, but see it's right there in the docs repo. So I can add it to the datasheet.  I'll submit a PR for Brett to review when he's back in the office.

**Comment by gbrault** [comment]
And actually where can I find the Memory map reference for photon? I am interested to understand how much memory is left for the user: Flash and RAM ...

**Comment by kennethlimcp** [comment]
@gbrault the Web IDE tells you that.. Same goes using Particle Dev or every building it locally.

For Web IDE: https://docs.particle.io/guide/getting-started/build/photon/#checking-code-memory-usage

**Comment by kennethlimcp** [comment]
closing this with: https://docs.particle.io/datasheets/photon-datasheet/#memory-map
