### ISSUE TITLE
Unclear description of "user safe mode"

### ISSUE THREAD

**Issue by rephorm** [particle-iot/docs#83]
The docs currently describe "user safe mode" with the following sentences:

"This is the most frequently mode, because your user application will not execute.  This can be useful if you have a bug in your code that is keeping you from re-flashing it over the air, or causing other hanging issues."

Is the first sentence trying to say that this mode is typically used when the user application will not execute? These sentences seem to indicate that this mode resets the device in a way that lets you always re-flash over the air (although it doesn't actually say that).

If my guess about the meaning is correct, I would reword this as something like:

"This mode will allow your device to be re-flashed over the air even if your application hangs the device or has a bug that otherwise prevents you from re-flashing."

**Comment by kennethlimcp** [comment]
This mode allows you to place the device manually in a safe state where no user code is running, hereby allowing an OTA/cloud interaction.

Also, this mode is activated when there is no user application for execution.

**Comment by rephorm** [comment]
Thanks, Kenneth. PR created.

**Comment by kennethlimcp** [comment]
@rephorm check out the new docs and see if the safe mode description is better now. Otherwise, i can review this and pull it in. Thanks!

**Comment by rephorm** [comment]
Hey, sorry I never got back to you before. The new descriptions are great! Thanks.
