### ISSUE TITLE
String::c_str() is missing from the docs

### ISSUE THREAD

**Issue by damonmaria** [particle-iot/docs#852]
[Here](https://prerelease-docs.particle.io/reference/firmware/electron/#string-class). I would edit it myself but all I know is what's in the [Arduino docs](https://www.arduino.cc/reference/en/language/variables/data-types/string/functions/c_str/) and I'm not sure of the copyright situation of copying that.

**Comment by rickkas7** [comment]
Thank you for the bug report. I added documentation for it:

https://docs.particle.io/reference/firmware/photon/#c_str-
