### ISSUE TITLE
Mobile page show "Guide" option

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/docs#860]
I don't think `Guide` is a header option anymore on the desktop site so we should fix this for the mobile site.

<img width="398" alt="screen shot 2018-10-27 at 08 15 53" src="https://user-images.githubusercontent.com/6760914/47597380-ceb95200-d9c0-11e8-8780-be22bd05f1a0.png">

**Comment by rickkas7** [comment]
Thank you for the report. Fixed via: https://github.com/particle-iot/docs/pull/863
