### ISSUE TITLE
Exact Ublox module for the Boron not clear

### ISSUE THREAD

**Issue by johanso-au** [particle-iot/docs#865]
The datasheet section only refers to a "Ublox SARA R410" module, however Ublox manufactures two variations of this module.

The module used in the Boron (as confirmed by Rick K on the forums) is the SARA-R410M-02B. This specific information is important to the international community in determining if the module has local carrier compatibility and certification.

Adding the "-02B" to the module references gives enough information to be able to ensure local network compatibility.

**Comment by johanso-au** [comment]
It would also be a good idea to add the 4G bands supported, being "Cat M1/NB1 bands: 2, 3, 4, 5, 8, 12, 13, 20, 28".

**Comment by rickkas7** [comment]
Fixed via: https://github.com/particle-iot/docs/pull/918
