### ISSUE TITLE
Particle.publish() still documented as having a 255 byte limit

### ISSUE THREAD

**Issue by nrobinson2000** [particle-iot/docs#877]
In the Docs it says the following:
<blockquote>
Cloud events have the following properties:

* name (1–63 ASCII characters)

Note: Only use letters, numbers, underscores, dashes and slashes in event names. Spaces and special characters may be escaped by different tools and libraries causing unexpected results.

* public/private (default public)

* ttl (time to live, 0–16777215 seconds, default 60) !! NOTE: The user-specified ttl value is not yet implemented, so changing this property will not currently have any impact.

* optional data (up to 255 bytes)
</blockquote>

Wasn't the limit raised?

I currently have a photon on `0.8.0-rc.7` that can publish events with 300+ character payloads without any problems.

**Comment by rickkas7** [comment]
The docs will be updated when 0.8.0 is a default release. Since 0.7.0 is still the default release, and 0.8.0 is a pre-release, the docs still have the lower limit.

**Comment by nrobinson2000** [comment]
Ahh, I see. Thanks for the clarification.

**Comment by technobly** [comment]
That said, it is currently documented now in the prerelease-docs: https://prerelease-docs.particle.io/reference/firmware/photon/#cloud-functions

**Comment by rickkas7** [comment]
Docs have been updated as of the 1.0.0 release.
