### ISSUE TITLE
Inconsistent api documentation syntax

### ISSUE THREAD

**Issue by TechplexEngineer** [particle-iot/docs#886]
The REST API endpoint "Definition" inconsistently shows optional arguments with square brackets around them.

For example [get a stream of events](https://docs.particle.io/reference/device-cloud/api/#get-a-stream-of-events) correctly shows: ```GET /v1/events/:eventPrefix``` as eventPrefix is required.

However [get a stream of your events](https://docs.particle.io/reference/device-cloud/api/#get-a-stream-of-your-events) incorrectly shows ```GET /v1/devices/events/:eventPrefix``` where it should be ```GET /v1/devices/events/[:eventPrefix]``` as eventPrefix is not required.

Also Incorrect:
- https://docs.particle.io/reference/device-cloud/api/#get-a-stream-of-events-for-a-device

Further why does the nomenclature change from eventPrefix to eventName when the documentation describes both fields as having the same prefix matching function?

Suggest changing the below to use "eventPrefix" rather than "eventName" for consistency
- `GET /v1/products/:productIdOrSlug/events/[:eventName]`
- `GET /v1/products/:productIdOrSlug/devices/:id/events/[:eventName]`

**Comment by monkbroc** [comment]
Thanks for pointing out the inconsistency.

**Comment by TechplexEngineer** [comment]
@monkbroc I would have sent a pull request but couldn't figure out how the "auto generated" magic works

**Comment by monkbroc** [comment]
Thanks for trying fix this yourself. These docs are generated from a private repository.

**Comment by monkbroc** [comment]
This change is now live. Thanks again for pointing it out. Cheers!

**Comment by TechplexEngineer** [comment]
Thanks for fixing it so quickly! I really appreciate the superb documentation and ease of getting started with particle devices, Kudos to you and the team!
