### ISSUE TITLE
[mesh] Documentation which pins are available for attachInterrupt()

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/docs#901]
Docs currently only list what pins are interrupt enabled for Gen1 & 2 devices.
Which pins can be used on mesh devices and is there any difference in usage (e.g. implicit application of internal pull-resistors)?

**Comment by rickkas7** [comment]
The docs now include pin information for mesh devices:

> All A and D pins (including TX, RX, and SPI) on 3rd generation (mesh) devices can be used for interrupts, however you can only attach interrupts to 8 pins at the same time.
