### ISSUE TITLE
Cloud Connection LED Blink Errors

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#910]
## [Existing docs:](https://docs.particle.io/tutorials/device-os/led/photon/#red-blink-basic-errors)
```
Red Blink Basic Errors
Blinking red indicates various errors.

2 red blinks: Could not reach the internet.
3 red blinks: Connected to the internet, but could not reach the Particle Device Cloud.
Blinking "orange": This sometimes is seen as yellow or red and indicates bad server keys.
Alternating cyan and red blinks can also indicate a keys issue.
```

Docs indicate wrong color and has some missing information.  
## Suggested correction:
```
Cloud Connection LED Blink Errors

While connecting to the Cloud, the RGB LED will be blinking cyan followed by:
- 1 orange blink: Decryption error.
- 2 orange blinks: Could not reach the internet.
- 3 orange blinks: Connected to the internet, but could not reach the Particle Device Cloud (This sometimes is seen as yellow or red and indicates bad server keys).
- 1 magenta blink: Authentication error.
- 1 red blink: generic handshake error (device could have the wrong keys or has just encountered a generic error in the handshake process)
```

## References

https://github.com/particle-iot/firmware/blob/b9aee446d630face6880e1e0f67554009e84b2f5/system/src/system_task.cpp#L259-L273

Notice here this code never sets the LED to RED, since Spark_Error_Count is only ever 0, 2 or 3:
https://github.com/particle-iot/firmware/blob/b9aee446d630face6880e1e0f67554009e84b2f5/system/src/system_task.cpp#L241-L244

Handshake errors blip the LED red once in a different part of the code here:
https://github.com/particle-iot/firmware/blob/b9aee446d630face6880e1e0f67554009e84b2f5/system/src/system_task.cpp#L378-L385

Which can also blip Orange or Magenta once (undocumented).

**Comment by rickkas7** [comment]
Fixed via: https://github.com/particle-iot/docs/pull/911
