### ISSUE TITLE
All Caps on headings with function names

### ISSUE THREAD

**Issue by embedded-creations** [particle-iot/docs#92]
This is probably all over the docs, but I was looking at this section in particular:
http://docs.particle.io/photon/firmware/#communication-spi

It's not a huge deal, but it would be nice to use the correct capitalization of function names when they are headings.  

The heading on the left says "begin()", and the heading in the docs says "BEGIN()".  The function is actually called `begin()`.

This is probably a css setting you could change.  Maybe the formatting in markdown should be a combination of heading and code e.g.

```
# `begin()`
```
# `begin()`

**Comment by technobly** [comment]
Duplicate issue: https://github.com/spark/docs/issues/41 Please see the convo there, thanks!
