### ISSUE TITLE
boron i2c documentation showing photo of a spark core

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/docs#931]
page: https://docs.particle.io/reference/device-os/firmware/boron/#wire-i2c-

showing: 
<img width="1289" alt="screen shot 2019-01-31 at 4 22 34 pm" src="https://user-images.githubusercontent.com/833793/52094563-78861d00-2574-11e9-8447-f01c6e64e386.png">

expected result: should show a photo of a boron.

**Comment by rickkas7** [comment]
Fixed

**Comment by rickkas7** [comment]
https://github.com/particle-iot/docs/commit/a84914aa095cbd5c6224cd9423042a6d91983662
